madsmtm/objc2

- objc-sys/CHANGELOG.md
- objc-sys/src/types.rs
- objc2-encode/examples/ns_uinteger.rs
- objc2-foundation/src/comparison_result.rs
See code comment for why these can be `isize` and `usize` instead of [how `cocoa` defines them](https://github.com/servo/core-foundation-rs/blob/cocoa-foundation-v0.1.0/cocoa-foundation/src/foundation.rs#L19-L27).
> Add `NSInteger` and `NSUInteger` to `objc-sys`

- .github/workflows/apple.yml
- .github/workflows/gnustep.yml
- objc-sys/build.rs
- objc-sys/src/various.rs
- objc2-foundation/src/enumerator.rs
- objc2/src/exception.rs
Added 32-bit support testing in CI, this revealed a few issues that I've also now fixed.
Unfortunately, GitHub Actions only support macOS 10.15 or above, which can't run 32-bit binaries, so they are only built on that platform; we'll have to rely on users with a macOS version of 10.14 or below (like me) to run the following to test it once in a while:
```sh
export SDKROOT=/path/to/downloaded/MacOSX10.13.sdk
cargo +nightly test -Z build-std --target i686-apple-darwin
cargo +nightly test -Z build-std --target i686-apple-darwin --features exception,catch_all,verify_message
```
> Test 32-bit support in CI

- objc2-foundation/CHANGELOG.md
- objc2-foundation/examples/class_with_lifetime.rs
- objc2-foundation/examples/custom_class.rs
- objc2-foundation/src/array.rs
- objc2-foundation/src/copying.rs
- objc2-foundation/src/data.rs
- objc2-foundation/src/dictionary.rs
- objc2-foundation/src/macros.rs
- objc2-foundation/src/object.rs
- objc2-foundation/src/string.rs
- objc2-foundation/src/value.rs
Instead, it is present on the types that actually need it. This is in preparation for bigger changes to `objc2-foundation`, see https://github.com/madsmtm/objc2/issues/58.
> Remove `INSObject::Ownership`

- objc2-foundation/CHANGELOG.md
- objc2-foundation/src/array.rs
- objc2-foundation/src/data.rs
- objc2-foundation/src/dictionary.rs
- objc2-foundation/src/macros.rs
- objc2-foundation/src/object.rs
- objc2-foundation/src/string.rs
- objc2-foundation/src/value.rs
- objc2/CHANGELOG.md
- objc2/src/rc/ownership.rs
Make the `object_struct` macro support generics
> Refactor `objc2-foundation` macros

- block-sys/CHANGELOG.md
- block-sys/src/lib.rs
- objc-sys/CHANGELOG.md
- objc-sys/src/lib.rs
- objc2-foundation/CHANGELOG.md
- objc2-foundation/src/array.rs
- objc2-foundation/src/data.rs
- objc2-foundation/src/dictionary.rs
- objc2-foundation/src/object.rs
- objc2-foundation/src/string.rs
- objc2-foundation/src/value.rs
- objc2/CHANGELOG.md
- objc2/src/declare.rs
- objc2/src/rc/autorelease.rs
- objc2/src/runtime.rs
https://github.com/madsmtm/objc2/pull/19 made `objc2::runtime` types `!Send`, `!Sync`, `!Unpin`, `!UnwindSafe` and `!RefUnwindSafe`.
This PR rectifies that for: `Ivar`, `Method`, `Class` and `Protocol`.
`Object` is intentionally still `!Send` and `!Sync`, since its subclasses are not guaranteed to be thread safe.
> `Send` and `Sync` fixes

- objc2-encode/CHANGELOG.md
- objc2-encode/src/encode.rs
- objc2/CHANGELOG.md
- objc2/src/runtime.rs
- `impl RefEncode for runtime::Protocol`
- `impl Encode for Option<fn-pointers>`
- `impl RefEncode for Option<fn-pointers>`
> Add a few more encoding impls

- .github/workflows/apple.yml
- .github/workflows/gnustep.yml
- objc2/CHANGELOG.md
- objc2/Cargo.toml
- objc2/examples/introspection.rs
- objc2/src/message/mod.rs
- objc2/src/runtime.rs
Helps cutting down on dependencies.
`malloc` transitively enables the `libc` crate, which is rarely needed and adds to download and compile times.
With this PR a clean build of `objc2-foundation` goes from ~7 seconds to ~5.5 seconds.
> Add `"malloc"` feature

- block2/CHANGELOG.md
- block2/src/global.rs
- block2/src/lib.rs
- tests/Cargo.toml
- tests/extern/block_utils.c
- tests/src/ffi.rs
- tests/src/lib.rs
Defines a `static` containing a `GlobalBlock`. This can be used directly in Objective-C (without the need for `_Block_copy`) and so can be quite convenient. (And is also more efficient).
TODO: ~Figure out whether the naming is proper (`fn` snake_case to `static` UPPER_CASE). See [C-CASE](https://rust-lang.github.io/api-guidelines/naming.html#c-case)~ Done.
> Add `global_block!` macro

- objc2-foundation/CHANGELOG.md
- objc2-foundation/src/array.rs
- objc2-foundation/src/dictionary.rs
- objc2-foundation/src/enumerator.rs
- objc2-foundation/src/object.rs
- objc2/CHANGELOG.md
- objc2/src/declare.rs
- objc2/src/message/mod.rs
- objc2/src/rc/autorelease.rs
- objc2/src/rc/id.rs
- objc2/src/rc/id_forwarding_impls.rs
- objc2/src/rc/id_traits.rs
- objc2/src/rc/weak_id.rs
- objc2/src/runtime.rs
To prepare for `extern type`s, precursor to #73.
> Relax `Sized` bounds where easily possible

- objc-sys/Cargo.toml
- objc2/Cargo.toml
This _probably_ fixes it, see the [build log](https://docs.rs/crate/objc-sys/0.2.0-alpha.0/builds/480939).
Previous attempt: #89.
> Fix `docs.rs` configuration

- block-sys/README.md
- block-sys/src/lib.rs
- objc-sys/README.md
- objc-sys/helper-scripts/gen-git.fish
- objc-sys/src/exception.rs
- objc-sys/src/lib.rs
- objc2/src/message/apple/x86.rs
- objc2/src/message/apple/x86_64.rs
- objc2/src/rc/autorelease.rs
Apple's https://opensource.apple.com/ page recently changed their links; they now provide stuff on GitHub (yet still without change history or reasoning beyond what exists in the code), so my unofficial mirrors are obsolete.
> Link official `git` sources

- .github/workflows/ci.yml
- objc-sys/CHANGELOG.md
- objc-sys/src/class.rs
- objc-sys/src/exception-macos-x86.rs
- objc-sys/src/exception.rs
- objc-sys/src/lib.rs
- objc-sys/src/message.rs
- objc-sys/src/method.rs
- objc-sys/src/object.rs
- objc-sys/src/property.rs
- objc-sys/src/protocol.rs
- objc-sys/src/rc.rs
- objc-sys/src/selector.rs
- objc-sys/src/various.rs
And test it in CI!
In reality, it doesn't _really_ matter that they are correctly `cfg`-guarded, because they're just not gonna be available on the platforms anyhow, but I think it's a good idea to ensure, so that you get compile-time errors instead of obscure linker errors.
> Ensure that `objc-sys` symbols have the correct `#[cfg]` guards

- block-sys/CHANGELOG.md
- block-sys/Cargo.toml
- block-sys/src/lib.rs
- block2/CHANGELOG.md
- block2/Cargo.toml
- block2/src/lib.rs
- objc-sys/CHANGELOG.md
- objc-sys/Cargo.toml
- objc-sys/src/lib.rs
- objc2-encode/CHANGELOG.md
- objc2-encode/Cargo.toml
- objc2-encode/src/lib.rs
- objc2-foundation/CHANGELOG.md
- objc2-foundation/Cargo.toml
- objc2-foundation/src/lib.rs
- objc2/CHANGELOG.md
- objc2/Cargo.toml
- objc2/src/lib.rs
This is mostly to roll out the fix for the failing `objc-sys` docs (see #89).
I've also added entries to the changelogs for when a significant dependency has been updated; this will become less relevant as we get more stable versions of `objc-sys` and `objc2-encode`.
> New versions

- objc2/CHANGELOG.md
- objc2/src/runtime.rs
While I still think it was correct to rename them in https://github.com/madsmtm/objc2/pull/102, having these makes migration from `objc` much easier; we can always remove the deprecations again at a later stage.
> (Re)add deprecated ivar methods

- .github/workflows/ci.yml
- objc2/src/lib.rs
- objc2/src/rc/autorelease.rs
Helps catching more bugs, and will be needed when we want to ensure more advanced optimizations
> Also test in release mode in CI

- objc2-encode/src/encode.rs
- objc2-encode/src/encoding.rs
- objc2/CHANGELOG.md
- objc2/src/exception.rs
- objc2/src/rc/autorelease.rs
- objc2/src/rc/weak_id.rs
- objc2/src/runtime.rs
Part of #26.
I looked through the [runtime part of `objrs`](https://gitlab.com/objrs/objrs/-/tree/b4f6598696b3fa622e6fddce7aff281770b0a8c2/src) and incorporated mostly comments from there.
That project is triple-licensed under the Apache License (Version 2.0), MIT license, or Mozilla Public License (Version 2.0), so this should be fine.
> Take inspiration from `objrs`

- objc2-encode/CHANGELOG.md
- objc2-encode/src/encoding.rs
- objc2-encode/src/lib.rs
- objc2-foundation/src/enumerator.rs
- tests/Cargo.toml
- tests/build.rs
- tests/extern/encode_utils.m
- tests/src/lib.rs
- tests/src/test_encode_utils.rs
Part of https://github.com/madsmtm/objc2/issues/68
These currently fail on macOS 32bit ~because of weird differences in `long` encodings~ (tested with `cargo +nightly test --target=i686-apple-darwin -Zbuild-std`) (**won't fix**):
```rust
test_encode_utils::ENCODING_INTPTR
test_encode_utils::ENCODING_INTPTR_ATOMIC
// test_encode_utils::ENCODING_LONG
// test_encode_utils::ENCODING_LONG_ATOMIC
// test_encode_utils::ENCODING_LONG_POINTER
test_encode_utils::ENCODING_SIZE_T
test_encode_utils::ENCODING_SIZE_T_ATOMIC
test_encode_utils::ENCODING_UINTPTR
test_encode_utils::ENCODING_UINTPTR_ATOMIC
// test_encode_utils::ENCODING_UNSIGNED_LONG
// test_encode_utils::ENCODING_UNSIGNED_LONG_ATOMIC
// test_encode_utils::ENCODING_UNSIGNED_LONG_POINTER
```
~Though on GNUStep 32bit, only these fail:~
```rust …
```
> Properly test that encodings match the Objective-C `@encode` output

- objc2-foundation/src/object.rs
- objc2/CHANGELOG.md
- objc2/src/bool.rs
- objc2/src/declare.rs
- objc2/src/exception.rs
- objc2/src/lib.rs
- objc2/src/message/mod.rs
- objc2/src/rc/id.rs
- objc2/src/rc/weak_id.rs
- objc2/src/runtime.rs
`Bool::as_bool`, `Id::new_null`, `Id::as_ptr` and `Id::retain_null`.
I found these to be convenient when manually creating bindings in #93
> Add a few helper functions

- objc2-foundation/CHANGELOG.md
- objc2-foundation/examples/basic_usage.rs
- objc2-foundation/examples/class_with_lifetime.rs
- objc2-foundation/examples/custom_class.rs
- objc2-foundation/src/array.rs
- objc2-foundation/src/copying.rs
- objc2-foundation/src/data.rs
- objc2-foundation/src/dictionary.rs
- objc2-foundation/src/enumerator.rs
- objc2-foundation/src/lib.rs
- objc2-foundation/src/macros.rs
- objc2-foundation/src/object.rs
- objc2-foundation/src/string.rs
- objc2-foundation/src/value.rs
- objc2/src/rc/id.rs
Huge part of https://github.com/madsmtm/objc2/issues/58.
Also renamed protocols, now that the possible confusion from them is gone.
(Yes, there exists both the `NSObject` class and the `NSObject` protocol, but that is something we'll paper over).
> Use `Deref` in `objc2-foundation` and remove "`INS`" helper traits

- .github/workflows/ci.yml
- objc2-foundation/src/array.rs
- objc2-foundation/src/object.rs
- objc2-foundation/src/string.rs
- objc2-foundation/src/value.rs
- objc2/src/rc/autorelease.rs
- objc2/src/runtime.rs
- tests/Cargo.toml
- tests/src/lib.rs
- tests/ui/autoreleasepool_not_send_sync.rs
- tests/ui/autoreleasepool_not_send_sync.stderr
- tests/ui/global_block_not_encode.rs
- tests/ui/global_block_not_encode.stderr
- tests/ui/msg_send_no_return_type.rs
- tests/ui/msg_send_no_return_type.stderr
- tests/ui/msg_send_not_encode.rs
- tests/ui/msg_send_not_encode.stderr
- tests/ui/msg_send_only_message.rs
- tests/ui/msg_send_only_message.stderr
- tests/ui/nsarray_bound_not_send_sync.rs
- tests/ui/nsarray_bound_not_send_sync.stderr
- tests/ui/nsstring_as_str_use_after_release.rs
- tests/ui/nsstring_as_str_use_after_release.stderr
- tests/ui/nsstring_as_str_use_outside_pool.rs
- tests/ui/nsstring_as_str_use_outside_pool.stderr
- tests/ui/nsvalue_f32_not_eq.rs
- tests/ui/nsvalue_f32_not_eq.stderr
- tests/ui/object_not_send_sync.rs
- tests/ui/object_not_send_sync.stderr
Unsure if I want to add this, similar functionality is achievable using `compile_fail` doctests, though this is a lot better at testing proper error messages.
> Use `trybuild` for testing compilation failures

- .github/workflows/ci.yml
- objc2/Cargo.toml
- objc2/benches/autorelease.rs
- objc2/src/rc/autorelease.rs
- objc2/src/rc/id.rs
- objc2/src/rc/id_traits.rs
- objc2/src/rc/weak_id.rs
Important for https://github.com/madsmtm/objc2/pull/104 and https://github.com/madsmtm/objc2/pull/81.
This took _wayyy_ longer than expected, but hey, I guess I learned a lot about Valgrind and such in the process!
Findings:
- `criterion` is pretty good, though I didn't really get the output stability from it that I would have liked; though that's to be expected when measuring wall clock time. Using [`criterion-cpu-time`](https://crates.io/crates/criterion-cpu-time) (others: [`criterion-cycles-per-byte`](https://crates.io/crates/criterion-cycles-per-byte), [`criterion-linux-perf`](https://crates.io/crates/criterion-linux-perf) or [`criterion-perf-events`](https://crates.io/crates/criterion-perf-events)) I did manage to get the output a bit more stable, but not enough to really say …
> Start benchmarking

- block-sys/src/lib.rs
- objc-sys/src/lib.rs
- objc2-foundation/src/array.rs
- objc2/src/rc/id.rs
- tests/ui/nsarray_bound_not_send_sync.stderr
- tests/ui/object_not_send_sync.stderr
- Properly mark objects as mutable behind shared references.
- Fix auto trait impls, see https://github.com/rust-lang/rust/issues/93367.
> Soundness fixes

- .github/workflows/ci.yml
- tests/ui/msg_send_only_message.stderr
- tests/ui/nsvalue_f32_not_eq.stderr
Follow up on #35.
The UI tests' output currently differs between `stable` and `nightly`, and that is gonna keep happening. I'm fine with having to "keep up" with changes (and reporting them if significant), but it'll be difficult to try to work around them being different between releases.
~Requires #128.~
> Only run UI tests on `nightly`

- objc2/CHANGELOG.md
- objc2/src/lib.rs
Helps with documentation.
Related: #134.
> Expose `objc2-encode` under `objc2::encode`

- objc2-foundation/examples/class_with_lifetime.rs
- objc2-foundation/examples/custom_class.rs
- objc2-foundation/src/enumerator.rs
- objc2/src/rc/autorelease.rs
- objc2/src/rc/id.rs
- objc2/src/rc/mod.rs
- objc2/src/rc/weak_id.rs
`Id<T, O>` and `WeakId<T>` should be covariant over `T`; this is now fixed for `WeakId`, and tested.
> Ensure covariance

- .github/workflows/ci.yml
- Cargo.toml
- tests/Cargo.toml
- tests/assembly/test_msg_send_zero_cost/Cargo.toml
- tests/assembly/test_msg_send_zero_cost/expected/aarch64-apple-darwin.s
- tests/assembly/test_msg_send_zero_cost/expected/aarch64-apple-ios-sim.s
- tests/assembly/test_msg_send_zero_cost/expected/aarch64-apple-ios.s
- tests/assembly/test_msg_send_zero_cost/expected/armv7-apple-ios.s
- tests/assembly/test_msg_send_zero_cost/expected/armv7s-apple-ios.s
- tests/assembly/test_msg_send_zero_cost/expected/i386-apple-ios.s
- tests/assembly/test_msg_send_zero_cost/expected/i686-apple-darwin.s
- tests/assembly/test_msg_send_zero_cost/expected/x86_64-apple-darwin.s
- tests/assembly/test_msg_send_zero_cost/expected/x86_64-apple-ios.s
- tests/assembly/test_msg_send_zero_cost/lib.rs
- tests/build.rs
- tests/src/bin/test_assembly.rs
Replaces #107.
This is fine for now, but will be tweaked further as specific needs arise (for example in #104 and #81). Would have been nicer if we could just have used a pre-made tool (like `trybuild`), but doesn't seem like one exist yet.
Noting [`filecheck`](https://docs.rs/filecheck/0.5.0/filecheck/) from [`wasmtime`'s tests](https://github.com/bytecodealliance/wasmtime/blob/df37074218fe1e94a767e780e2138dde4dbd264c/cranelift/docs/testing.md#filecheck) again, if I find I need it in the future.
> Assembly tests

- .github/workflows/ci.yml
- objc2-foundation/examples/class_with_lifetime.rs
- objc2-foundation/examples/custom_class.rs
- objc2-foundation/src/array.rs
- objc2-foundation/src/attributed_string.rs
- objc2-foundation/src/copying.rs
- objc2-foundation/src/data.rs
- objc2-foundation/src/dictionary.rs
- objc2-foundation/src/enumerator.rs
- objc2-foundation/src/macros.rs
- objc2-foundation/src/mutable_attributed_string.rs
- objc2-foundation/src/mutable_string.rs
- objc2-foundation/src/object.rs
- objc2-foundation/src/process_info.rs
- objc2-foundation/src/string.rs
- objc2-foundation/src/thread.rs
- objc2-foundation/src/uuid.rs
- objc2-foundation/src/value.rs
- objc2/CHANGELOG.md
- objc2/README.md
- objc2/benches/autorelease.rs
- objc2/examples/introspection.rs
- objc2/examples/talk_to_me.rs
- objc2/src/exception.rs
- objc2/src/lib.rs
- objc2/src/rc/id.rs
- objc2/src/rc/mod.rs
- objc2/src/rc/weak_id.rs
`Option::unwrap_unchecked` is stable since 1.58, and that is IMO much clearer than wrapping things in `NonNull` beforehand (see the changelog entry for an example).
The real motivation for this change is from https://github.com/madsmtm/objc2/pull/81, where the naive implementation of `Id::retain_autoreleased_null` would have been completely broken (the extra branch in `NonNull::new(ptr).map(|ptr| unsafe { Id::retain_autoreleased(ptr) })` would interfere).
Also, looking through the code I seem to have used `NonNull::new_unchecked` a lot more than what's entirely correct (`+ alloc`/`+ new` can return `nil` when out of memory), so changing those to `unwrap` makes things better in that regard (albeit a tiny bit slower).
> Change null handling when creating `Id`s

- .github/workflows/ci.yml
- objc2-foundation/src/array.rs
- objc2-foundation/src/dictionary.rs
- objc2-foundation/src/enumerator.rs
- objc2-foundation/src/object.rs
- objc2-foundation/src/process_info.rs
- objc2-foundation/src/thread.rs
- objc2/CHANGELOG.md
- objc2/benches/autorelease.rs
- objc2/src/rc/id.rs
- objc2/tests/id_retain_autoreleased.rs
- tests/assembly/test_retain_autoreleased/Cargo.toml
- tests/assembly/test_retain_autoreleased/expected/aarch64-apple-darwin.s
- tests/assembly/test_retain_autoreleased/expected/aarch64-apple-ios-sim.s
- tests/assembly/test_retain_autoreleased/expected/aarch64-apple-ios.s
- tests/assembly/test_retain_autoreleased/expected/armv7-apple-ios.s
- tests/assembly/test_retain_autoreleased/expected/armv7s-apple-ios.s
- tests/assembly/test_retain_autoreleased/expected/i386-apple-ios.s
- tests/assembly/test_retain_autoreleased/expected/i686-apple-darwin.s
- tests/assembly/test_retain_autoreleased/expected/x86_64-apple-darwin.s
- tests/assembly/test_retain_autoreleased/expected/x86_64-apple-ios.s
- tests/assembly/test_retain_autoreleased/lib.rs
- tests/src/bin/test_assembly.rs
An optimized version of `Id::retain` that uses `objc_retainAutoreleasedReturnValue` for when the previous caller returns an autoreleased value with `objc_autoreleaseReturnValue`. This is a common thing in ARC code to avoid unnecessary `autorelease/retain` pairs, but it is (apart from changing the retain count) purely an optimization.
This uses the [newly stabilized](https://github.com/rust-lang/rust/pull/91728) inline assembly, which can easily cause _very_ undefined behaviour if used incorrectly. Luckily, the instructions are exceedingly simple (essentially just a special `nop`), so there's almost no room for error - so fingers crossed I got this right (at least enough that it doesn't cause UB)!
I've tested this on my local machine (both x86 and x86_64), and I've also added assembly …
> Add `Id::retain_autoreleased`

- objc2-encode/CHANGELOG.md
- objc2-encode/src/encode.rs
- objc2-encode/src/encoding.rs
- objc2-encode/src/lib.rs
- objc2-encode/src/parse.rs
- objc2-foundation/src/enumerator.rs
- objc2/CHANGELOG.md
- objc2/src/message/mod.rs
- tests/build.rs
- tests/extern/encode_utils.m
- tests/src/test_encode_utils.rs
Made a few breaking changes and documentation updates, I feel fairly confident in publishing a stable `v2.0.0` soon
> Pushing `objc2-encode` closer to `v2.0.0`

- objc2-foundation/src/array.rs
- objc2-foundation/src/data.rs
- objc2-foundation/src/macros.rs
- objc2-foundation/src/mutable_attributed_string.rs
- objc2-foundation/src/mutable_string.rs
- objc2-foundation/src/object.rs
This allows converting objects to their superclasses directly (instead of e.g. going through `Deref`).
> Impl `AsRef` and `AsMut` for objects, to convert them to their superclasses

- objc2-encode/src/lib.rs
- objc2-encode/src/static_str.rs
Will be used at some point when generic constants are available, see https://github.com/madsmtm/objc2/pull/70, but makes sense to merge into the main codebase now for maintainability.
> Add const functions to generate a `&'static str` from Encoding

- objc2-encode/src/encode.rs
- objc2-foundation/examples/class_with_lifetime.rs
- objc2-foundation/examples/custom_class.rs
- objc2-foundation/src/array.rs
- objc2/CHANGELOG.md
- objc2/src/declare.rs
- objc2/src/test_utils.rs
- tests/ui/fn_ptr_reference_encode.rs
- tests/ui/fn_ptr_reference_encode.stderr
- tests/ui/fn_ptr_reference_encode2.rs
- tests/ui/fn_ptr_reference_encode2.stderr
- tests/ui/fn_ptr_reference_method.rs
- tests/ui/fn_ptr_reference_method.stderr
- tests/ui/fn_ptr_reference_method2.rs
- tests/ui/fn_ptr_reference_method2.stderr
Part of #30.
Rename `ClassDecl` to `ClassBuilder` and make `ClassBuilder::add_method` more ergonomic.
> Slightly better class declaration

- objc2-foundation/examples/custom_class.rs
- objc2-foundation/src/array.rs
- objc2-foundation/src/attributed_string.rs
- objc2-foundation/src/data.rs
- objc2-foundation/src/dictionary.rs
- objc2-foundation/src/enumerator.rs
- objc2-foundation/src/mutable_attributed_string.rs
- objc2-foundation/src/mutable_string.rs
- objc2-foundation/src/string.rs
- objc2-foundation/src/value.rs
- objc2/CHANGELOG.md
- objc2/benches/autorelease.rs
- objc2/examples/introspection.rs
- objc2/examples/talk_to_me.rs
- objc2/src/declare.rs
- objc2/src/lib.rs
- objc2/src/macros.rs
- objc2/src/message/mod.rs
- objc2/src/rc/id.rs
- objc2/src/rc/weak_id.rs
- objc2/src/test_utils.rs
- tests/assembly/test_msg_send_zero_cost/lib.rs
- tests/assembly/test_retain_autoreleased/lib.rs
- tests/src/test_object.rs
- tests/ui/msg_send_mutable.rs
- tests/ui/msg_send_mutable.stderr
- tests/ui/msg_send_not_encode.rs
- tests/ui/msg_send_not_encode.stderr
- tests/ui/msg_send_only_message.stderr
Resolves upstream issue https://github.com/SSheldon/rust-objc/issues/112.
Whichever solution we choose has quite the large effect on https://github.com/madsmtm/objc2/pull/120, since we'd like `msg_send!` and `msg_send_id!` to be consistent, and e.g. `msg_send_id!` sometimes needs the ability to consume its arguments.
This PR is a stab at implementing idea 3 as outlined in https://github.com/SSheldon/rust-objc/issues/112#issuecomment-1134422347. Not quite happy with the fact that we use fully qualified method calls, which means reborrows are sometimes necessary (see diff in `objc2-foundation/src/array.rs` and `objc2-foundation/src/data.rs`, may or may not be a big problem in practice?).
I'm reluctant to do idea 2 (add `msg_send_mut!`) since we would also need `msg_send_bool_mut!` and …
> Change how mutability in `msg_send!` is done

- objc2-encode/src/encode.rs
- objc2/CHANGELOG.md
- objc2/src/message/mod.rs
- tests/ui/fn_ptr_reference_encode.rs
- tests/ui/fn_ptr_reference_encode.stderr
- tests/ui/fn_ptr_reference_encode2.rs
- tests/ui/fn_ptr_reference_encode2.stderr
- tests/ui/fn_ptr_reference_method.rs
- tests/ui/fn_ptr_reference_method2.rs
- tests/ui/fn_ptr_reference_method2.stderr
This was added in error, really, there is no case where we would want `T: Message` to include `ManuallyDrop<T>` - that would simply only serve to confuse the user, as they might think the `dealloc` method wouldn't be called for `Id<ManuallyDrop<MyObject>, O>`, which it definitely would!
> Remove `Message` impl for `ManuallyDrop` + fix UI test

- objc2-foundation/CHANGELOG.md
- objc2-foundation/src/array.rs
- objc2-foundation/src/attributed_string.rs
- objc2-foundation/src/data.rs
- objc2-foundation/src/macros.rs
- objc2-foundation/src/mutable_attributed_string.rs
- objc2-foundation/src/mutable_string.rs
- objc2-foundation/src/object.rs
- objc2-foundation/src/string.rs
- objc2-foundation/src/uuid.rs
- objc2-foundation/src/value.rs
Part of #67.
Implement `AsRef`/`AsMut` that forward to objects themselves.
Implement `Borrow`/`BorrowMut` for objects.
Implement `ToOwned` using `NSCopying`/`NSMutableCopying` where appropriate.
> More foundation traits

- block-sys/Cargo.toml
- block-sys/build.rs
- block2/Cargo.toml
- objc-sys/Cargo.toml
- objc-sys/build.rs
- objc2-encode/Cargo.toml
- objc2-foundation/Cargo.toml
- objc2/Cargo.toml
Tested with local [`docs.rs`](https://github.com/rust-lang/docs.rs) instance.
Tier 3 (and below) targets are not yet supported, see https://github.com/rust-lang/docs.rs/issues/1561
> Set `docs.rs` targets on all crates

- block2/src/global.rs
- block2/src/lib.rs
- objc2-foundation/src/array.rs
- objc2-foundation/src/data.rs
- objc2-foundation/src/enumerator.rs
- objc2-foundation/src/macros.rs
- objc2-foundation/src/string.rs
- objc2-foundation/src/value.rs
- objc2/examples/talk_to_me.rs
- objc2/src/cache.rs
- objc2/src/declare.rs
- objc2/src/exception.rs
- objc2/src/message/apple/mod.rs
- objc2/src/message/gnustep.rs
- objc2/src/message/mod.rs
- objc2/src/rc/autorelease.rs
- objc2/src/rc/id_traits.rs
- objc2/src/runtime.rs
- objc2/src/test_utils.rs
- objc2/tests/id_retain_autoreleased.rs
Fix mutability of pointers when sending a message to `&mut T`, the pointer was coerced using `&mut T -> &T`, which gives the wrong provenance.
`Fix NSArray::new` returning an `Owned` object - Found while experimenting with verification using associated objects in https://github.com/madsmtm/objc2/pull/127.
> Small soundness fixes and code cleanup

- objc2/src/rc/id.rs
- objc2/src/rc/mod.rs
- objc2/src/rc/test_object.rs
- objc2/src/rc/weak_id.rs
Having problems with this on GNUStep!
~Might be fixed in v2.0, see https://github.com/gnustep/libobjc2/commit/722a2c3b0d706c1403c8fdf9858737143412d03a~ Nope.
I'll just disable the parts that don't work for now
> Add test helper `RcTestObject` to test that reference counting works properly

- .github/workflows/ci.yml
- objc2/src/lib.rs
Already found a bug that prevented examples from running, will help a lot with https://github.com/madsmtm/objc2/pull/104 in the future.
This won't really slow our CI runs down, since the linux machines that these run on have much higher availability (we're only allowed a certain number of concurrent macOS instances, so our CI is currently waiting a lot on that).
Couldn't easily get v1.7 and v1.8 up n' running, so I guess we won't test those yet.
> Test `libobjc2` v2.0 and v2.1 as well

- .github/workflows/ci.yml
- block-sys/src/lib.rs
- block2/src/lib.rs
- objc-sys/src/constants.rs
- objc-sys/src/lib.rs
- objc-sys/src/types.rs
- objc2-encode/src/lib.rs
- objc2-encode/src/parse.rs
- objc2-encode/src/static_str.rs
- objc2-foundation/examples/basic_usage.rs
- objc2-foundation/src/array.rs
- objc2-foundation/src/attributed_string.rs
- objc2-foundation/src/data.rs
- objc2-foundation/src/lib.rs
- objc2-foundation/src/mutable_attributed_string.rs
- objc2-foundation/src/mutable_string.rs
- objc2-foundation/src/range.rs
- objc2-foundation/src/string.rs
- objc2/src/lib.rs
- objc2/src/message/mod.rs
- objc2/src/rc/id.rs
- objc2/src/rc/test_object.rs
- objc2/src/rc/weak_id.rs
- tests/src/ffi.rs
- tests/src/lib.rs
- tests/src/test_encode_utils.rs
- tests/src/test_object.rs
The `clippy::let_unit_value` lint triggers unnecessarily on `nightly`, see https://github.com/rust-lang/rust-clippy/issues/8998.
> Run clippy in CI

- objc2/CHANGELOG.md
- objc2/src/cache.rs
- objc2/src/declare.rs
- objc2/src/macros.rs
- objc2/src/message/gnustep.rs
- objc2/src/runtime.rs
Basically everything will crash if the selector is NULL.
Also fixes soundness issues in OOM situations.
> Make `Sel` contain `NonNull` allowing more optimizations

- .github/workflows/ci.yml
- block-sys/Cargo.toml
- block-sys/src/lib.rs
- block2/Cargo.toml
- block2/src/lib.rs
- objc-sys/Cargo.toml
- objc-sys/src/lib.rs
- objc2-encode/Cargo.toml
- objc2-encode/src/lib.rs
- objc2-foundation/Cargo.toml
- objc2-foundation/src/lib.rs
- objc2/Cargo.toml
- objc2/src/lib.rs
- tests/Cargo.toml
- tests/assembly/test_msg_send_id/Cargo.toml
- tests/assembly/test_msg_send_static_sel/Cargo.toml
- tests/assembly/test_msg_send_zero_cost/Cargo.toml
- tests/assembly/test_retain_autoreleased/Cargo.toml
- tests/assembly/test_static_sel/Cargo.toml
Add `std` and `alloc` features, with `std` being a default (that the user must turn off using `--no-default-features`)
> Prepare for a time when we can make the crates `no_std`

- .github/workflows/ci.yml
- objc-sys/CHANGELOG.md
- objc-sys/Cargo.toml
- objc-sys/src/class.rs
- objc-sys/src/exception.rs
- objc-sys/src/lib.rs
- objc-sys/src/message.rs
- objc-sys/src/protocol.rs
- objc-sys/src/rc.rs
- objc-sys/src/various.rs
- objc2-encode/Cargo.toml
- objc2-encode/src/encode.rs
- objc2-encode/src/lib.rs
- objc2-foundation/src/array.rs
- objc2-foundation/src/geometry.rs
- objc2/CHANGELOG.md
- objc2/Cargo.toml
- objc2/src/declare.rs
- objc2/src/exception.rs
- objc2/src/lib.rs
- objc2/src/message/mod.rs
- objc2/src/runtime.rs
- objc2/src/test_utils.rs
Upstream: https://github.com/SSheldon/rust-objc-exception/pull/11
Requires https://github.com/rust-lang/rust/issues/74990
> Unstable: Make calling `throw` no longer UB by using "C-unwind"

- objc2/CHANGELOG.md
- objc2/src/lib.rs
- objc2/src/message/mod.rs
- objc2/src/message/verify.rs
- objc2/src/runtime.rs
- objc2/src/verify.rs
Move `MessageReceiver::verify_message` to `Class::verify_msg_send`.
I intend to make further changes, but want to merge this now to preserve `git` history.
> Refactor message verification functionality

- objc2/CHANGELOG.md
- objc2/src/message/mod.rs
- objc2/src/rc/id.rs
- objc2/src/runtime.rs
Part of https://github.com/madsmtm/objc2/issues/87. Related: https://github.com/madsmtm/objc2/issues/58.
Also slightly changes the contract of `Message` to support it, though those requirements were basically already true.
> Add `Id::cast`

- objc2/CHANGELOG.md
- objc2/src/__macro_helpers.rs
- objc2/src/lib.rs
- objc2/src/macros.rs
- objc2/src/message/apple/mod.rs
- objc2/src/message/gnustep.rs
- objc2/src/message/mod.rs
- objc2/src/runtime.rs
- objc2/src/verify.rs
- tests/assembly/test_msg_send_id/lib.rs
- tests/assembly/test_msg_send_zero_cost/lib.rs
- tests/assembly/test_retain_autoreleased/lib.rs
- tests/ui/msg_send_id_invalid_receiver.stderr
- tests/ui/msg_send_mutable.stderr
`MessageError` has been removed, instead we now expose a `VerificationError` (which is much more specific about what it actually does, and avoids allocations). Manual usage of `MessageReceiver::send_message` now no longer need to handle the error case.
Also, errors that `verify_message` catches are now more consistent:
```
thread 'main' panicked at 'Method initA not found on class NSObject'
thread 'main' panicked at 'Return type code I does not match expected Q for method hash'
thread 'main' panicked at 'invalid message send to -[NSObject initA]: method not found'
thread 'main' panicked at 'invalid message send to -[NSObject hash]: expected return to have type code Q, but found I'
```
> Improve message verification and error handling

- objc2/CHANGELOG.md
- objc2/src/__macro_helpers.rs
- objc2/src/macros.rs
- objc2/src/rc/allocated.rs
- objc2/src/rc/id.rs
- objc2/src/rc/mod.rs
- tests/assembly/test_msg_send_id/lib.rs
- tests/ui/msg_send_id_invalid_receiver.rs
- tests/ui/msg_send_id_invalid_receiver.stderr
- tests/ui/msg_send_id_invalid_return.rs
- tests/ui/msg_send_id_invalid_return.stderr
~Blocked on https://github.com/madsmtm/objc2/pull/120.~
Add a new user facing opaque struct `rc::Allocated<T>`, which is intended to be used inside `Id` as `Id<Allocated<T>, O>`, and can be gotten from `msg_send_id![cls, alloc]`. This will help users differentiate between allocated and initialized objects.
See also https://github.com/madsmtm/objc2/issues/87 for more discussion about why we want this.
TODO:
> Add `rc::Allocated`

- objc2/src/declare.rs
- objc2/src/rc/id.rs
Part of https://github.com/madsmtm/objc2/issues/30.
Calls `objc_autoreleaseReturnValue`. Required for most custom declared methods that return objects.
> Add `Id::autorelease_return`

- README.md
- objc2-foundation/examples/class_with_lifetime.rs
- objc2-foundation/examples/custom_class.rs
- objc2/CHANGELOG.md
- objc2/src/declare.rs
- objc2/src/rc/id.rs
- objc2/src/rc/test_object.rs
- objc2/src/test_utils.rs
- tests/ui/fn_ptr_reference_method.rs
- tests/ui/fn_ptr_reference_method.stderr
- tests/ui/fn_ptr_reference_method2.rs
- tests/ui/fn_ptr_reference_method2.stderr
Part of https://github.com/madsmtm/objc2/issues/30. This is required for https://github.com/madsmtm/objc2/pull/190.
Fixes upstream https://github.com/SSheldon/rust-objc/issues/12, see that for more details.
Previously, the receiver's lifetime was higher-ranked, while the rest of the arguments weren't, which meant that:
- Their type could not be inferred like the other arguments
- Having a return type with a lifetime bound to the receiver was impossible
This is a breaking change (can't avoid that, lest we run into a future-compat error), and is unfortunately difficult for users to know how to fix, not really sure how to improve that situation?
> Consistently implement `MethodImplementation` wrt. lifetimes

- objc2-foundation/CHANGELOG.md
- objc2-foundation/examples/custom_class.rs
- objc2-foundation/examples/declaration.rs
- objc2-foundation/src/declare_macro.rs
- objc2-foundation/src/lib.rs
- objc2-foundation/src/macros.rs
- objc2-foundation/src/object.rs
- objc2-foundation/src/zone.rs
- objc2/CHANGELOG.md
- objc2/examples/declare_ivar.rs
- objc2/src/declare.rs
- objc2/src/declare/ivar.rs
- objc2/src/declare/ivar_forwarding_impls.rs
~Blocked on https://github.com/madsmtm/objc2/pull/193.~
Solves a big part of https://github.com/madsmtm/objc2/issues/30. Fixes upstream https://github.com/SSheldon/rust-objc/issues/74.
Related to https://github.com/madsmtm/objc2/pull/161, and has a few of the same limitations when it comes to defining methods.
Syntax:
```rust
declare_class! {
// Similar to `extern_class!`
// Implements protocol `NSApplicationDelegate`
unsafe struct CustomAppDelegate: NSResponder, NSObject <NSApplicationDelegate> {
pub ivar: u8,
another_ivar: Bool,
}
unsafe impl {
@sel(abc:defGhi:)
fn abc_def_ghi(&self, arg1: &Object, arg2: i32) {
println!("{}", self.ivar + arg2);
}
}
}
// Generates
pub struct ivar;
unsafe impl objc2::declare::IvarType for ivar {
type Type = u8;
const NAME: &'static str = "ivar";
}
struct …
```
> `declare_class!` macro

- block2/src/global.rs
- objc-sys/build.rs
- objc2-foundation/src/macros.rs
- objc2/CHANGELOG.md
- objc2/Cargo.toml
- objc2/src/declare.rs
- objc2/src/lib.rs
- objc2/src/message/apple/mod.rs
- objc2/src/rc/autorelease.rs
- objc2/src/rc/id.rs
- objc2/src/rc/mod.rs
- objc2/src/rc/weak_id.rs
- objc2/src/runtime.rs
- tests/extern/encode_utils.m
- tests/src/test_encode_utils.rs
- Add extra tests
- Note stuff in `Id` found when creating #197
- Re-add `Sel::as_ptr`, is required for [cacao](https://github.com/ryanmcgrath/cacao), see https://github.com/ryanmcgrath/cacao/pull/30.
- Improve `extern_class!` safety docs
- Fix spelling
> Smaller fixes

- block-sys/CHANGELOG.md
- block-sys/src/lib.rs
- objc-sys/CHANGELOG.md
- objc-sys/src/class.rs
- objc-sys/src/constants.rs
- objc-sys/src/exception.rs
- objc-sys/src/lib.rs
- objc-sys/src/message.rs
- objc-sys/src/method.rs
- objc-sys/src/object.rs
- objc-sys/src/property.rs
- objc-sys/src/protocol.rs
- objc-sys/src/rc.rs
- objc-sys/src/selector.rs
- objc-sys/src/various.rs
- objc2-foundation/Cargo.toml
- objc2-foundation/src/lib.rs
- objc2/Cargo.toml
- objc2/src/lib.rs
This is possible since `docs.rs` always uses `nightly` Rust.
Tracking issue: https://github.com/rust-lang/rust/issues/43781
> Use `doc_auto_cfg` on docs.rs

- block2/src/lib.rs
- objc2-foundation/src/array.rs
- objc2-foundation/src/attributed_string.rs
- objc2-foundation/src/data.rs
- objc2-foundation/src/declare_macro.rs
- objc2-foundation/src/dictionary.rs
- objc2-foundation/src/exception.rs
- objc2-foundation/src/lib.rs
- objc2-foundation/src/macros.rs
- objc2-foundation/src/mutable_attributed_string.rs
- objc2-foundation/src/mutable_string.rs
- objc2-foundation/src/object.rs
- objc2-foundation/src/process_info.rs
- objc2-foundation/src/string.rs
- objc2-foundation/src/thread.rs
- objc2-foundation/src/uuid.rs
- objc2-foundation/src/value.rs
- objc2/src/__macro_helpers.rs
- objc2/src/declare.rs
- objc2/src/declare/ivar.rs
- objc2/src/exception.rs
- objc2/src/lib.rs
- objc2/src/message/mod.rs
- objc2/src/rc/autorelease.rs
- objc2/src/rc/id.rs
- objc2/src/rc/test_object.rs
- objc2/src/runtime.rs
- objc2/src/test_utils.rs
- objc2/src/verify.rs
Remove internal `unsafe_def_fn` macro and all instances of `#[macro_use]`
> Macro cleanup

- test-assembly/src/lib.rs
Funny this should break now, right after https://github.com/madsmtm/objc2/pull/209.
First time that nightlies broke these tests, so that's pretty good, definitely better than our UI tests!
> Fix nightly assembly tests

- objc2-foundation/CHANGELOG.md
- objc2-foundation/examples/declaration.rs
- objc2-foundation/src/declare_macro.rs
- objc2-foundation/src/macros.rs
I found a way to make it look like ordinary Rust attributes, without using a proc macro, so yay!
> Change selector syntax in `declare_class!` macro

- Cargo.toml
- objc2/src/__macro_helpers.rs
- objc2/src/macros.rs
- test-assembly/crates/test_msg_send_static_sel/expected/apple-aarch64.s
- test-assembly/crates/test_msg_send_static_sel/expected/apple-armv7.s
- test-assembly/crates/test_msg_send_static_sel/expected/apple-armv7s.s
- test-assembly/crates/test_msg_send_static_sel/expected/apple-old-x86.s
- test-assembly/crates/test_msg_send_static_sel/expected/apple-x86.s
- test-assembly/crates/test_msg_send_static_sel/expected/apple-x86_64.s
- test-assembly/crates/test_static_sel/expected/apple-aarch64.s
- test-assembly/crates/test_static_sel/expected/apple-armv7.s
- test-assembly/crates/test_static_sel/expected/apple-armv7s.s
- test-assembly/crates/test_static_sel/expected/apple-old-x86.s
- test-assembly/crates/test_static_sel/expected/apple-x86.s
- test-assembly/crates/test_static_sel/expected/apple-x86_64.s
- test-assembly/src/main.rs
Deduplicate selectors `alloc`, `init` and `new`, both when generating statics for these, and when caching said selectors.
> Deduplicate common selectors

- objc2-foundation/src/array.rs
- objc2/src/rc/ownership.rs
- test-ui/ui/msg_send_id_invalid_return.stderr
- test-ui/ui/msg_send_id_underspecified.stderr
This helps when using in generic code.
Also make the fact that they are empty enums private.
> Make traits that `Owned` and `Shared` implement supertraits of `Ownership`

- .github/workflows/ci.yml
- objc2-foundation/src/thread.rs
- tests/extern/encode_utils.m
- tests/src/test_encode_utils.rs
GitHub Actions has deprecated support for that OS version, and it will be fully removed in a month, see https://github.com/actions/virtual-environments/issues/5583
> No longer test on macOS 10.15

- .github/workflows/ci.yml
This was disabled in #99 with the reasoning:
> It's annoying to not get full feedback the first time around, and it prevents the other builds from finishing their caching
While this is still true, I find myself often manually cancelling CI runs when I've seen something fail, because that will free up some macOS instances for my account, and thus enabling the next run to complete much faster.
> Re-enable fail-fast in CI

- objc2/src/foundation/value.rs
- objc2/src/runtime.rs
Introduced in #226, but wasn't caught because #228 hadn't been merged yet
> Fix NSValue geometry getters

- objc2/CHANGELOG_FOUNDATION.md
- objc2/src/foundation/error.rs
- objc2/src/foundation/mod.rs
- test-ui/ui/msg_send_id_invalid_return.stderr
Inspiration from:
- https://github.com/SSheldon/rust-objc-foundation/pull/16
- https://github.com/nvzqz/fruity/tree/v0.3.0/src/foundation/ns_error
- https://github.com/ryanmcgrath/cacao/blob/02946476837e45ee381e37dde2946ed63b44dc31/src/error.rs
> Add basic version of `NSError`

- objc2-encode/CHANGELOG.md
- objc2-encode/src/encoding.rs
- objc2-encode/src/helper.rs
- objc2-encode/src/parse.rs
- objc2-encode/src/static_str.rs
- objc2/src/__macro_helpers.rs
- objc2/src/foundation/zone.rs
- tests/extern/encode_utils.m
- tests/src/test_encode_utils.rs
Structs within two pointer indirections (amongst others) should have their fields stripped from the resulting encoding string; `objc2-encode` doesn't handle this yet (it is context-unaware), this PR is an attempt to fix that.
> Fix nested encodings

- objc2/CHANGELOG.md
- objc2/CHANGELOG_FOUNDATION.md
- objc2/src/__macro_helpers.rs
- objc2/src/foundation/array.rs
- objc2/src/foundation/data.rs
- objc2/src/foundation/dictionary.rs
- objc2/src/foundation/mod.rs
- objc2/src/foundation/mutable_array.rs
- objc2/src/foundation/mutable_data.rs
- objc2/src/foundation/value.rs
- objc2/src/macros/declare_class.rs
- objc2/src/macros/extern_class.rs
- objc2/src/rc/test_object.rs
- test-ui/ui/nsarray_bound_not_send_sync.stderr
- tests/src/exception.rs
Part of https://github.com/madsmtm/objc2/issues/67.
I took a look at how we do arrays again, and while a bit confusing with the double-ownership (e.g. `Id<Array<T, O1>, O2>`), I'm now fairly confident that it is sound.
> Improve safety in foundation collection types wrt. ownership

- objc2/CHANGELOG.md
- objc2/examples/class_with_lifetime.rs
- objc2/src/declare.rs
- objc2/src/declare/ivar.rs
- objc2/src/macros/declare_class.rs
Part of https://github.com/madsmtm/objc2/issues/30.
Helper method for adding an `declare::Ivar<T>` to a class. Simplifies manual usage of ivars a bit.
> Add `ClassBuilder::add_static_ivar`

- objc2/CHANGELOG.md
- objc2/src/foundation/array.rs
- objc2/src/foundation/attributed_string.rs
- objc2/src/foundation/data.rs
- objc2/src/foundation/dictionary.rs
- objc2/src/foundation/error.rs
- objc2/src/foundation/exception.rs
- objc2/src/foundation/mutable_array.rs
- objc2/src/foundation/mutable_attributed_string.rs
- objc2/src/foundation/mutable_data.rs
- objc2/src/foundation/mutable_string.rs
- objc2/src/foundation/object.rs
- objc2/src/foundation/process_info.rs
- objc2/src/foundation/string.rs
- objc2/src/foundation/thread.rs
- objc2/src/foundation/uuid.rs
- objc2/src/foundation/value.rs
- objc2/src/macros.rs
- objc2/src/macros/declare_class.rs
- objc2/src/macros/extern_methods.rs
Replaces https://github.com/madsmtm/objc2/pull/161.
Syntax:
```rust
extern_methods!(
// `unsafe` here signifies that 
unsafe impl NSData {
#[sel_id(new)] // TODO: Doesn't work yet!
pub fn new() -> Id<Self, Shared>;
#[sel(length)]
pub fn len(&self) -> usize;
// This has a body, and hence is not touched at all
pub fn is_empty(&self) -> bool {
self.len() == 0
}
#[sel(bytes)]
fn bytes_raw(&self) -> *const c_void;
}
);
// Becomes:
impl NSData {
pub fn new() -> Id<Self, Shared> {
unsafe { msg_send_id![Self::class(), new].expect("unexpected NULL NSData") }
}
pub fn len(&self) -> usize {
unsafe { msg_send![self, length] }
}
pub fn is_empty(&self) -> bool {
self.len() == 0
}
#[sel(bytes)]
fn bytes_raw(&self) -> *const c_void;
}
```
TODO:
- Postponed. See #239 for the `msg_send_bool` situation. …
> Add `extern_methods!` macro

- block2/CHANGELOG.md
- block2/src/block.rs
- block2/src/concrete_block.rs
- block2/src/global.rs
- test-ui/ui/global_block_not_encode.stderr
Part of https://github.com/madsmtm/objc2/issues/168.
Required for the soundness of #239 (`EncodeArguments` will be relaxed to `EncodeConvert`, while `block2` relied on it being `Encode`)
> Clean up block traits

- test-ui/ui/global_block_not_encode.stderr
- test-ui/ui/msg_send_id_invalid_receiver.stderr
- test-ui/ui/msg_send_id_invalid_return.stderr
- test-ui/ui/msg_send_not_encode.stderr
- test-ui/ui/nsarray_bound_not_send_sync.stderr
Rust 1.65 seems to have updated their error messages for missing trait implementations which caused some UI tests to fail.
> Update UI tests for Rust 1.65 nightly

- objc2/src/foundation/mod.rs
- objc2/src/foundation/mutable_set.rs
- objc2/src/foundation/set.rs
- test-ui/ui/msg_send_id_invalid_return.stderr
- test-ui/ui/msg_send_super_not_classtype.stderr
`NSSet` and `NSMutableSet` have a lot in common with `NSArray` and `NSDictionary`, so they were relatively straightforward to add.
Part of #67.
> Add `NSSet` and `NSMutableSet`

- objc2/CHANGELOG.md
- objc2/examples/class_with_lifetime.rs
- objc2/examples/delegate.rs
- objc2/src/declare/ivar.rs
Part of #30.
This could be solved in many ways, including some type-safe ways like creating a new `PartialInit` struct containing `MaybeUninit`, but I went with the pragmatic solution for now.
> Better ivar initialization

- objc2/CHANGELOG.md
- objc2/examples/delegate.rs
- objc2/src/__macro_helpers.rs
- objc2/src/declare.rs
- objc2/src/declare/ivar.rs
- objc2/src/declare/ivar_drop.rs
- objc2/src/declare/ivar_forwarding_impls.rs
- objc2/src/macros/declare_class.rs
- objc2/src/runtime.rs
Part of https://github.com/madsmtm/objc2/issues/30.
The desire is to allow using `Box`, `Id` and `WeakId` (and at some point `Arc`, `Rc` and the corresponding `Weak`) inside instance variables.
This is accomplished using a new user-facing type `IvarDrop<T>` (because of current coherence limitations in how `Box`/`#[fundamental]` types work).
Usage:
```rust
use objc2::foundation::NSObject;
use objc2::declare::IvarDrop;
use objc2::{declare_class, ClassType};
declare_class!(
struct MyObject {
ivar: IvarDrop<Box<i32>>,
}
unsafe impl ClassType for MyObject {
type Super = NSObject;
}
// Later on, initialize it with `Ivar::write`
// A `dealloc` method is generated automatically
);
```
> Allow `Drop` types in ivars

- objc2/CHANGELOG_FOUNDATION.md
- objc2/src/foundation/attributed_string.rs
- objc2/src/foundation/bundle.rs
- objc2/src/foundation/mod.rs
- objc2/src/foundation/string.rs
- test-ui/ui/msg_send_id_invalid_return.stderr
- test-ui/ui/msg_send_super_not_classtype.stderr
Part of https://github.com/madsmtm/objc2/issues/67.
A few additions to `objc2::foundation` to make it easier to [use in `winit`](https://github.com/rust-windowing/winit/pull/2427).
> `objc2::foundation` additions for `winit`

- objc2/CHANGELOG.md
- objc2/examples/class_with_lifetime.rs
- objc2/examples/delegate.rs
- objc2/src/class_type.rs
- objc2/src/foundation/object.rs
- objc2/src/macros/declare_class.rs
- objc2/src/macros/extern_class.rs
- objc2/src/rc/test_object.rs
- tests/src/test_object.rs
Allow directly specifying class name in `declare_class!` macro using `ClassType::NAME`.
> Add `ClassType::NAME`

- objc2/CHANGELOG.md
- objc2/examples/speech_synthethis.rs
- objc2/src/foundation/object.rs
- objc2/src/macros.rs
- objc2/src/macros/declare_class.rs
- objc2/src/macros/extern_class.rs
Similar to https://github.com/madsmtm/objc2/pull/259.
Personally, I'd always name the type the same thing, but I can see the utility in allowing the user control over this (and `metal` wants to control this with `extern_protocol!` from #250)
> Allow specifying `ClassType::NAME` in `extern_class!` macro

- objc2/CHANGELOG.md
- objc2/src/__macro_helpers.rs
- objc2/src/macros.rs
- objc2/src/rc/test_object.rs
- test-ui/ui/msg_send_id_invalid_receiver.rs
- test-ui/ui/msg_send_id_invalid_receiver.stderr
Allow other types than `&Class` as the receiver in `msg_send_id!` methods of the `new` family.
This is useful in `metal`, for example [`-[MTLDevice newTextureWithDescriptor:]`](https://developer.apple.com/documentation/metal/mtldevice/1433425-newtexturewithdescriptor?language=objc).
> Any receiver in `msg_send_id!` new

- objc2/CHANGELOG.md
- objc2/src/__macro_helpers.rs
- objc2/src/declare.rs
- objc2/src/macros/declare_class.rs
- objc2/src/message/mod.rs
- objc2/src/runtime.rs
- objc2/src/test_utils.rs
- objc2/src/verify.rs
Add extra verification in `declare_class!`.
This would help even more if I knew why some protocols like `NSWindowDelegate` are not available at runtime.
Verify:
> Verify class declaration

- objc2/src/declare/ivar.rs
- objc2/src/foundation/error.rs
- objc2/src/foundation/thread.rs
- objc2/src/macros/declare_class.rs
- objc2/src/rc/test_object.rs
- objc2/src/rc/weak_id.rs
Run with:
```bash
ASAN_OPTIONS=detect_leaks=1 RUSTFLAGS="-Zsanitizer=address" cargo +nightly test --target=x86_64-apple-darwin -Zbuild-std --tests -- --skip=foundation::error::tests --skip=test_weak
```
Notably, I incorrectly assumed that the super class' `dealloc` method is called in custom `dealloc` methods, but this is only true in Objective-C with ARC enabled!
~Builds upon https://github.com/madsmtm/objc2/pull/273.~
> Run AddressSanitizer and fix leak

- objc2/CHANGELOG.md
- objc2/src/macros/__rewrite_self_arg.rs
- objc2/src/macros/declare_class.rs
- objc2/src/macros/extern_methods.rs
- objc2/src/rc/test_object.rs
- test-ui/ui/extern_methods_wrong_arguments.rs
- test-ui/ui/extern_methods_wrong_arguments.stderr
Required for #244 as a workaround for [arbitrary self types](https://github.com/rust-lang/rust/issues/44874) or similar not being available.
> Add support for `this` marking an instance method in `extern_methods!`

- objc2/CHANGELOG.md
- objc2/src/foundation/array.rs
- objc2/src/foundation/attributed_string.rs
- objc2/src/foundation/bundle.rs
- objc2/src/foundation/data.rs
- objc2/src/foundation/dictionary.rs
- objc2/src/foundation/error.rs
- objc2/src/foundation/exception.rs
- objc2/src/foundation/mutable_array.rs
- objc2/src/foundation/mutable_attributed_string.rs
- objc2/src/foundation/mutable_data.rs
- objc2/src/foundation/mutable_dictionary.rs
- objc2/src/foundation/mutable_set.rs
- objc2/src/foundation/mutable_string.rs
- objc2/src/foundation/number.rs
- objc2/src/foundation/object.rs
- objc2/src/foundation/process_info.rs
- objc2/src/foundation/set.rs
- objc2/src/foundation/string.rs
- objc2/src/foundation/thread.rs
- objc2/src/foundation/uuid.rs
- objc2/src/macros/declare_class.rs
- objc2/src/macros/extern_class.rs
- objc2/src/macros/extern_methods.rs
- test-ui/ui/extern_methods_invalid_type.rs
- test-ui/ui/extern_methods_invalid_type.stderr
- test-ui/ui/extern_methods_missing_method.stderr
- test-ui/ui/extern_methods_selector_twice.rs
- test-ui/ui/extern_methods_selector_twice.stderr
Initial example syntax:
```rust
extern_methods!(
unsafe impl MyObject {
#[sel_id(init)]
fn new() -> Id<Self, Owned>;
#[sel_id(description)]
fn get(&self) -> Id<NSString, Owned>;
}
);
// Becomes
impl MyObject {
fn new() -> Id<Self, Owned> {
// Automatic allocation?
unsafe { msg_send_id![msg_send_id![Self::class(), alloc], init] }
}
fn get(&self) -> Id<NSString, Owned> {
unsafe { msg_send_id![self, description] }
}
}
```
> Allow returning `Id` from `extern_methods!`

- crates/objc2-encode/CHANGELOG.md
- crates/objc2-encode/src/encoding.rs
- crates/objc2-encode/src/encoding_box.rs
- crates/objc2-encode/src/helper.rs
- crates/objc2-encode/src/lib.rs
- crates/objc2-encode/src/parse.rs
- crates/objc2-encode/src/static_str.rs
- crates/objc2/src/verify.rs
- fuzz/.gitignore
- fuzz/Cargo.toml
- fuzz/fuzz_targets/encoding_parse.rs
Required for https://github.com/madsmtm/objc2/pull/198.
This requires us to reimplement a few things from the Objective-C runtime, but that functionality is broken for complex types anyhow, and doing this ourselves will hopefully allow us to make _much_ better error messages in the future.
> Add `EncodingBox`, and methods to parse it from a string

- .github/workflows/ci.yml
- crates/objc2-encode/src/encoding_box.rs
- crates/objc2-encode/src/parse.rs
- crates/objc2/CHANGELOG.md
- crates/objc2/Cargo.toml
- crates/objc2/src/__macro_helpers.rs
- crates/objc2/src/declare.rs
- crates/objc2/src/lib.rs
- crates/objc2/src/macros.rs
- crates/objc2/src/macros/declare_class.rs
- crates/objc2/src/message/mod.rs
- crates/objc2/src/rc/test_object.rs
- crates/objc2/src/runtime.rs
- crates/objc2/src/runtime/method_encoding_iter.rs
- crates/objc2/src/verify.rs
- crates/objc2/tests/id_retain_autoreleased.rs
- crates/tests/src/exception.rs
- helper-scripts/test-local.fish
- Always only on `debug_assertions`
- Most of it is enabled by default
- The rest can be enabled with the `"verify"` feature
This will also allow better error messages in the future, ideally the error would state the required change to your `Encode`/`RefEncode` implementation.
TODO:
> Rework verification feature selection

- .github/workflows/ci.yml
- crates/objc2/src/runtime.rs
The CI was a mistake in https://github.com/madsmtm/objc2/pull/308.
The missing NULL check was found by running with `-Zbuild-std` (which enables debug assertions for `std`)
> Fix CI and missing NULL check

- crates/objc2/src/declare.rs
- crates/objc2/src/message/apple/mod.rs
- crates/objc2/src/message/gnustep.rs
- crates/objc2/src/message/mod.rs
- crates/objc2/src/runtime.rs
- crates/objc2/src/verify.rs
This doesn't have any effect on `cargo check` (which currently takes ~21s), but makes a clean dev build of `Foundation` go from ~48s to ~34s (funnily, a release build is still quicker at ~29s).
Part of #311.
> Improve monomorphization

- crates/header-translator/src/method.rs
- crates/header-translator/src/rust_type.rs
- crates/icrate/src/Foundation/additions/lock.rs
- crates/icrate/src/Foundation/additions/mutable_array.rs
- crates/icrate/src/Foundation/additions/mutable_dictionary.rs
- crates/icrate/src/Foundation/additions/mutable_set.rs
- crates/icrate/src/Foundation/additions/thread.rs
- crates/icrate/src/Foundation/fixes/NSThread.rs
- crates/icrate/src/Foundation/fixes/generic_return.rs
- crates/objc2/CHANGELOG.md
- crates/objc2/src/macros/extern_methods.rs
- crates/objc2/tests/no_prelude.rs
- crates/test-ui/ui/extern_methods_invalid_type.rs
- crates/test-ui/ui/extern_methods_invalid_type.stderr
- crates/test-ui/ui/extern_methods_wrong_arguments.stderr
- crates/test-ui/ui/extern_methods_wrong_arguments_error.rs
- crates/test-ui/ui/extern_methods_wrong_arguments_error.stderr
- crates/test-ui/ui/msg_send_invalid_error.rs
- crates/test-ui/ui/wrong_optional.stderr
See the changelog and commits for details.
Inspired in part by https://github.com/madsmtm/objc2/issues/291#issuecomment-1364748151, this will improve the error message when the user specifies an invalid selector.
> Improve `extern_methods!`

- .github/workflows/ci.yml
- README.md
- crates/block-sys/Cargo.toml
- crates/block2/Cargo.toml
- crates/icrate/Cargo.toml
- crates/icrate/src/Foundation/additions/value.rs
- crates/icrate/src/Foundation/fixes/NSDecimal.rs
- crates/icrate/src/common.rs
- crates/objc-sys/Cargo.toml
- crates/objc2-encode/Cargo.toml
- crates/objc2-proc-macros/Cargo.toml
- crates/objc2/Cargo.toml
This is _not_ a MSRV policy, e.g. bumping the MSRV is still NOT a breaking change, see #203 for that.
> Make our current MSRV match `winit`'s

- .github/workflows/ci.yml
- crates/header-translator/framework-includes.h
- crates/header-translator/src/data/CoreAnimation.rs
- crates/header-translator/src/data/Metal.rs
- crates/header-translator/src/data/macros.rs
- crates/header-translator/src/data/mod.rs
- crates/header-translator/src/rust_type.rs
- crates/header-translator/src/stmt.rs
- crates/header-translator/src/unexposed_macro.rs
- crates/header-translator/translation-config.toml
- crates/icrate/Cargo.toml
- crates/icrate/src/Foundation/additions/mod.rs
- crates/icrate/src/Metal/capture.rs
- crates/icrate/src/Metal/device.rs
- crates/icrate/src/Metal/fixes.rs
- crates/icrate/src/Metal/mod.rs
- crates/icrate/src/Metal/private.rs
- crates/icrate/src/Metal/slice.rs
- crates/icrate/src/lib.rs
Including manually authored `unsafe`, which takes a lot of inspiration from the `metal` crate regarding what's `unsafe` (though there are probably still mistakes in this).
> Add Metal framework

- Cargo.lock
- crates/header-translator/Cargo.toml
- crates/header-translator/src/cache.rs
- crates/header-translator/src/data/README.md
- crates/header-translator/src/file.rs
- crates/header-translator/src/lib.rs
- crates/header-translator/src/library.rs
- crates/header-translator/src/method.rs
- crates/header-translator/src/output.rs
- crates/header-translator/src/property.rs
- crates/header-translator/src/rust_type.rs
- crates/header-translator/src/stmt.rs
- crates/header-translator/src/unexposed_macro.rs
- crates/header-translator/translation-config.toml
- crates/icrate/src/Foundation/__ns_string.rs
- crates/objc2/src/__macro_helpers.rs
I basically redid the whole "parse lifetime from a string"-part, and tweaked a lot of other small things (a lot of these were small irritating things that were preventing me from doing "real" work like https://github.com/madsmtm/objc2/pull/328)
> Various header translator refactors

- .github/workflows/ci.yml
- crates/header-translator/src/context.rs
- crates/header-translator/src/data/Metal.rs
- crates/header-translator/src/id.rs
- crates/header-translator/src/main.rs
- crates/header-translator/translation-config.toml
- crates/icrate/CHANGELOG.md
- crates/icrate/Cargo.toml
- crates/icrate/README.md
- crates/icrate/src/common.rs
As suggested by @silvanshade.
Also using the trick they described in https://github.com/madsmtm/objc2/pull/326#issuecomment-1376649834 to get GitHub actions to work.
~(I need to download XCode 14.2 myself before I can finish this)~ done
> Update `icrate` SDK version

- crates/header-translator/translation-config.toml
- crates/objc2-proc-macros/CHANGELOG.md
- crates/objc2-proc-macros/src/lib.rs
- crates/objc2/CHANGELOG.md
- crates/objc2/src/__macro_helpers.rs
- crates/objc2/src/declare.rs
- crates/objc2/src/declare/declare_class_tests.rs
- crates/objc2/src/lib.rs
- crates/objc2/src/macros.rs
- crates/objc2/src/macros/__method_msg_send.rs
- crates/objc2/src/macros/__rewrite_self_arg.rs
- crates/objc2/src/macros/extern_methods.rs
- crates/objc2/src/macros/extern_protocol.rs
- crates/objc2/src/runtime.rs
- crates/objc2/src/test_utils.rs
- crates/objc2/src/verify.rs
- crates/test-ui/ui/extern_methods_bad_selector.rs
- crates/test-ui/ui/extern_methods_bad_selector.stderr
- crates/test-ui/ui/extern_methods_variadic.rs
- crates/test-ui/ui/extern_methods_variadic.stderr
- crates/test-ui/ui/extern_methods_wrong_arguments.stderr
- crates/test-ui/ui/invalid_sel.stderr
Should help cutting down on the amount of work https://github.com/madsmtm/objc2/pull/327 and futures has to do. Tagging @silvanshade.
> Allow multiple colons in selectors

- .github/workflows/ci.yml
- Cargo.lock
- crates/header-translator/Cargo.toml
- crates/test-assembly/Cargo.toml
- crates/test-ui/ui/extern_protocol_class_method.stderr
- crates/test-ui/ui/msg_send_underspecified_error.stderr
Previously, I've had it updated automatically, so that I could help find regressions in the compiler output faster.
But that's not really tenable now that there's starting to be other contributors to the project - so let's revert to manually updating said version (just like we do with out dependencies, which this PR also updates).
> Update our nightly version manually

- .github/workflows/ci.yml
- crates/header-translator/Cargo.toml
- crates/header-translator/README.md
- crates/header-translator/src/bin/check_icrate_features.rs
- crates/header-translator/src/lib.rs
- crates/test-assembly/Cargo.toml
- crates/test-assembly/src/lib.rs
- crates/test-assembly/src/main.rs
Previously, I was guarding these with a `run` cargo feature so that a simple `cargo test` wouldn't need to download all the dependencies. But nowadays, I only run `cargo test` on the specific crate I want to test, so the point is moot.
Also fixes the complaint that @silvanshade had in https://github.com/madsmtm/objc2/pull/333
> Make running `header-translator` and `test-assembly` easier

- .github/workflows/ci.yml
- Cargo.lock
- crates/icrate/CHANGELOG.md
- crates/icrate/Cargo.toml
- crates/icrate/src/Foundation/additions/uuid.rs
- crates/icrate/src/Foundation/mod.rs
- crates/icrate/tests/uuid.rs
It is very simple to do manually, and having the cargo feature may break if `uuid` crate's internals start using `icrate`.
> Remove the optional `uuid` integration from `icrate`

- Cargo.lock
- crates/icrate/Cargo.toml
- crates/icrate/src/Foundation/additions/mod.rs
- crates/icrate/src/Foundation/additions/thread.rs
- crates/icrate/tests/thread.rs
For wrapping types like `Id<NSWindow, Shared>` which is only safe to access from the main thread.
Should help pushing https://github.com/rust-windowing/winit/issues/2464 forwards.
Previous main thread work: https://github.com/madsmtm/objc2/issues/27
TODO:
> Add `MainThreadBound`

- crates/test-assembly/crates/test_ns_string/lib.rs
It seems these should be feature gated now otherwise they show errors.
> Fix errors in test-assembly

- crates/header-translator/src/data/Foundation.rs
- crates/header-translator/src/stmt.rs
- crates/icrate/src/macros.rs
- crates/icrate/tests/struct_encoding.rs
Fixes: #387 
Currently `header-translator` uses the struct typedef name as the struct name which is incorrect.
When Objc encodes structs it uses the struct name without any typedefs. E.g. the following struct has the internal struct name of `foo` and `@encode(bar) = {foo=q}`:
```
typedef struct foo {
NSInteger x;
} bar;
```
This pull request fixes the header translator to store the internal struct name separately from the potentially typedef'd identifier. Additionally the `extern_struct!` macro is modified to require a `#[struct_name("name")]` attribute to generate the proper `Encoding`.
Rerun `header-translator` and update [`icrate-generated`](https://github.com/madsmtm/icrate-generated/).
> Separate Rust struct type names and Objc internal struct names during header translations

- crates/objc2/src/__macro_helpers.rs
- crates/objc2/src/declare.rs
- crates/objc2/src/macros/declare_class.rs
- crates/objc2/tests/track_caller.rs
Since it's kinda fiddly to get to work, and e.g. doesn't work on closures yet - so it would be nice to actually test that we do it.
Required for #173
> Add `#[track_caller]` test

- crates/icrate/src/Foundation/additions/string.rs
- crates/objc2/CHANGELOG.md
- crates/objc2/Cargo.toml
- crates/objc2/src/declare.rs
- crates/objc2/src/exception.rs
- crates/objc2/src/protocol.rs
- crates/objc2/src/rc/autorelease.rs
- crates/objc2/src/rc/id.rs
- crates/objc2/src/rc/mod.rs
- crates/objc2/src/rc/test_object.rs
- crates/objc2/src/runtime/__nsstring.rs
- crates/test-ui/ui/autoreleasepool_not_send_sync.rs
- crates/test-ui/ui/autoreleasepool_not_send_sync.stderr
- crates/test-ui/ui/nsstring_as_str_use_outside_pool.stderr
- crates/tests/src/test_object.rs
- Move lifetime parameter onto the type (`&'p AutoreleasePool` -> `AutoreleasePool<'p>`)
- Make `Id` autorelease methods associated functions
- Add `autoreleasepool_leaking`
- Fix autorelease pools on unwind
- Further expand autorelease pool docs
> Redo autorelease pools

- crates/objc-sys/CHANGELOG.md
- crates/objc-sys/build.rs
- crates/objc-sys/extern/exception.m
- crates/objc-sys/src/constants.rs
- crates/objc-sys/src/image_info.rs
- crates/objc-sys/src/protocol.rs
- crates/objc-sys/src/types.rs
- crates/objc2/CHANGELOG.md
- crates/objc2/src/exception.rs
- crates/tests/src/exception.rs
The memory leaks are from redundant `autorelease`s, so they would likely eventually be cleaned up by the application, but still, it's inefficient.
> Fix memory leaks in exception handling

- .github/workflows/ci.yml
- crates/objc2/src/rc/id.rs
- crates/test-ui/ui/nsarray_bound_not_send_sync.stderr
Introduced in #419, but at the time I couldn't find a workaround for this issue, so I just decided to punt the issue, since I was going to be looking into changing iteration in https://github.com/madsmtm/objc2/issues/304 anyhow.
Today while working on https://github.com/madsmtm/objc2/pull/443, I stumbled upon a way to fix the problematic `rustdoc` ICE, so let's just do that!
> Fix generating documentation for structs containing `objc2::rc::Id`

- .github/workflows/ci.yml
- Cargo.lock
- crates/icrate/tests/mutable_array.rs
- crates/objc2/src/rc/test_object.rs
- crates/test-assembly/crates/test_autorelease_return/Cargo.toml
- crates/test-assembly/crates/test_autorelease_return/expected/apple-aarch64.s
- crates/test-assembly/crates/test_autorelease_return/expected/apple-armv7.s
- crates/test-assembly/crates/test_autorelease_return/expected/apple-armv7s.s
- crates/test-assembly/crates/test_autorelease_return/expected/apple-x86.s
- crates/test-assembly/crates/test_autorelease_return/expected/apple-x86_64.s
- crates/test-assembly/crates/test_autorelease_return/expected/gnustep-x86.s
- crates/test-assembly/crates/test_autorelease_return/expected/gnustep-x86_64.s
- crates/test-assembly/crates/test_autorelease_return/lib.rs
- crates/test-assembly/crates/test_fast_enumeration/expected/apple-armv7.s
- crates/test-assembly/crates/test_fast_enumeration/expected/apple-armv7s.s
- crates/test-assembly/crates/test_fast_enumeration/expected/apple-x86.s
- crates/test-assembly/src/lib.rs
During release of https://github.com/madsmtm/objc2/pull/464. All of this is just testing errors, no actual bugs were uncovered here (except perhaps for the missing autorelease).
> Fix errors found during release testing

- Cargo.lock
- crates/block-sys/Cargo.toml
- crates/block2/CHANGELOG.md
- crates/block2/Cargo.toml
- crates/block2/src/lib.rs
- crates/icrate/CHANGELOG.md
- crates/icrate/Cargo.toml
- crates/icrate/src/lib.rs
- crates/objc-sys/CHANGELOG.md
- crates/objc-sys/Cargo.toml
- crates/objc-sys/src/lib.rs
- crates/objc2-encode/CHANGELOG.md
- crates/objc2-encode/Cargo.toml
- crates/objc2-encode/src/lib.rs
- crates/objc2/CHANGELOG.md
- crates/objc2/Cargo.toml
- crates/objc2/src/lib.rs
We're going to go away from using pre-release versions; while they're nice for signalling instability, they're a real pain when you need to do patch releases, see e.g. https://github.com/rust-windowing/winit/pull/2739.
While we release both `objc2 v0.4` and `block2 v0.2`, these are not expected to be stable, and will still have frequent breaking changes. This is unfortunate, but unavoidable, and still better that we'd be able to patch these if e.g. winit requires it. I'll try to be harsher with `objc2-encode v2` though, since users expect more stability from such a version number, but I will not let it severely hinder development.
Checklist:
- `objc-sys`
- `objc2-encode`
- `objc2`
- `block2`
- `icrate`
- Local tests have been run (see `helper-scripts/test-local.fish`):
- Am not at the …
> New versions + stop using pre-release versioning

- .github/workflows/ci.yml
- crates/header-translator/translation-config.toml
- crates/icrate/Cargo.toml
This PR is a quick fix to add what appears to be a missing `AppKit` dependency to `AuthenticationServices`
To help with testing things, I hacked in the ability for `header-generator` to generate a feature that enables all `{library}_all` features, so I could trivially attempt to build the whole of `icrate`. Upon doing this, I discovered that `AuthenticationServices` failed to build with a missing import - everything else built successfully.
I am not entirely convinced this isn't a setup issue on my part, but I've pushed up this PR to at least start the discussion. FWIW, my build steps were simply:
```
cargo run --bin header-translator -- /Applications/Xcode_14.2.app/Contents/Developer/
cd crates/icrate
cargo build --features all_libraries
```
where `Xcode_14.2.app` is a direct download …
> Fix `AuthenticationServices` build

- Cargo.lock
- crates/header-translator/Cargo.toml
Not sure which particular proc-macro release fixed this but from their changelog I can see that some releases did have some changes around nightly features.
Edit: https://github.com/dtolnay/proc-macro2/releases/tag/1.0.60 probably fixed this.
> Update proc-macro dep so it compiles on nightly again

- crates/objc2/Cargo.toml
- crates/objc2/src/rc/allocated.rs
- crates/objc2/src/rc/id.rs
- crates/objc2/src/runtime/mod.rs
- crates/objc2/src/runtime/retain_release_fast.rs
Last year, Apple improved a few things in the Objective-C runtime and `clang`, see [this video from WWDC22](https://developer.apple.com/videos/play/wwdc2022/110363/). Last time I checked, these were not yet available in the open-source version of `clang`, though they might be by now.
We don't really have a good way to enable these automatically yet, see https://github.com/madsmtm/objc2/issues/266, but for now, we can implement these features behind a feature flag `unstable-apple-new`, for people to try them out!
TODO: Implement the optimized versions of:
- Not possible for us since our protocol checks are done using the runtime
> New Objective-C runtime features

- crates/objc2/CHANGELOG.md
- crates/objc2/src/macros/__method_msg_send.rs
- crates/objc2/src/macros/extern_methods.rs
- crates/objc2/tests/macros_mainthreadmarker.rs
- crates/test-ui/ui/extern_methods_invalid_type.rs
- crates/test-ui/ui/extern_methods_invalid_type.stderr
- crates/test-ui/ui/extern_methods_wrong_arguments_error.rs
- crates/test-ui/ui/extern_methods_wrong_arguments_error.stderr
Required for https://github.com/madsmtm/objc2/pull/359.
Unsure if this can be supported in `declare_class!`.
> Allow using `MainThreadMarker` in `extern_methods!`

- .github/workflows/ci.yml
- crates/objc2/src/__macro_helpers/declare_class.rs
- crates/objc2/src/declare/mod.rs
- crates/objc2/src/encode/__unstable.rs
- crates/objc2/src/message/mod.rs
- crates/objc2/src/rc/id.rs
- crates/objc2/src/rc/mod.rs
- crates/objc2/tests/declare_class_self.rs
- crates/objc2/tests/no_prelude.rs
- crates/objc2/tests/use_macros.rs
- crates/test-assembly/crates/test_declare_class/expected/apple-aarch64.s
- crates/test-assembly/crates/test_declare_class/expected/apple-armv7.s
- crates/test-assembly/crates/test_declare_class/expected/apple-armv7s.s
- crates/test-assembly/crates/test_declare_class/expected/apple-old-x86.s
- crates/test-assembly/crates/test_declare_class/expected/apple-x86.s
- crates/test-assembly/src/lib.rs
- crates/test-ui/ui/declare_class_invalid_receiver.rs
- crates/test-ui/ui/declare_class_invalid_receiver.stderr
- crates/test-ui/ui/declare_class_invalid_syntax.rs
- crates/test-ui/ui/declare_class_invalid_syntax.stderr
Test failures discovered while doing https://github.com/madsmtm/objc2/pull/476, and some preparatory work on https://github.com/madsmtm/objc2/issues/428.
> Improve `declare_class!` tests

- crates/objc2/CHANGELOG.md
- crates/objc2/Cargo.toml
- crates/objc2/src/verify.rs
Will help with https://github.com/servo/core-foundation-rs/pull/628, since a lot of CoreFoundation types are used there as just `*mut c_void`, and it would be really cumbersome and error-prone to have to change all of these to custom type aliases with a proper `Encode` implementation.
> Allow `c_void` pointers as return and argument types in more cases (behind a feature flag)

- crates/icrate/examples/browser.rs
It doesn't look like the browser example is currently being tested in CI either but I wasn't sure how to (re-)enable that.
> Fix browser example

- crates/icrate/CHANGELOG.md
- crates/icrate/README.md
- crates/icrate/examples/basic_usage.rs
- crates/icrate/examples/browser.rs
- crates/icrate/examples/delegate.rs
- crates/icrate/examples/speech_synthesis.rs
- crates/icrate/src/Foundation/additions/dictionary.rs
- crates/icrate/src/Foundation/additions/set.rs
- crates/icrate/src/Foundation/additions/string.rs
- crates/icrate/src/Foundation/macros/ns_string.rs
- crates/icrate/src/Foundation/mod.rs
- crates/icrate/src/lib.rs
- crates/icrate/tests/error.rs
- crates/icrate/tests/mutable_set.rs
- crates/icrate/tests/set.rs
- crates/icrate/tests/string.rs
- crates/objc2/CHANGELOG.md
- crates/test-assembly/crates/test_ns_string/lib.rs
- crates/test-ui/ui/invalid_ns_string_input.rs
- crates/test-ui/ui/invalid_ns_string_output.rs
- crates/test-ui/ui/ns_string_not_const.rs
- crates/test-ui/ui/ns_string_output_not_const.rs
- crates/test-ui/ui/ns_string_output_not_const.stderr
This is something that always annoyed me, but that I thought was unfixable since we use `macro_rules!`, and have everything in one crate; but I spotted this [tip](https://internals.rust-lang.org/t/pub-on-macro-rules/19358/16) today on IRLO, apparently it's possible!
> Move `ns_string!` macro to `Foundation` module

- .github/workflows/ci.yml
Just basic maintenance, [`actions-rs/toolchain`](https://github.com/actions-rs/toolchain) is unmaintained and has been so for a long time.
> Use `dtolnay/rust-toolchain` instead of `actions-rs/toolchain`

- crates/header-translator/src/output.rs
- crates/icrate/Cargo.toml
- crates/icrate/examples/metal.rs
This PR adds the Metal API example corresponding to the discussion at https://github.com/madsmtm/objc2/issues/483.
@PicoLeaf I merged your commits and did some final refactoring. Thanks for adding the animation part in there and creating the other PR.
> Metal example

- crates/icrate/CHANGELOG.md
- crates/icrate/src/Foundation/additions/thread.rs
- crates/objc2/CHANGELOG.md
- crates/objc2/src/mutability.rs
See the commits for details.
These are things I noticed while working with `MainThreadMarker` in `winit`.
> Change a few things in our main thread utilities

- crates/icrate/examples/browser.rs
- crates/icrate/examples/metal.rs
This PR refactors the `browser` and `metal` examples to use `OnceCell` instead of `RefCell`.
I feel this is a more precise representation of how those ivars are used since they are intended to only be initialized once, and it should be an error to try and set them again (in this case, although in other scenarios `RefCell` could certainly make sense).
As a nice side effect, it should be a little more efficient and we don't seem to need the inner `Option` either.
> Refactor browser and metal examples to use OnceCell

- crates/objc2/CHANGELOG.md
- crates/objc2/Cargo.toml
- crates/objc2/src/macros/__msg_send_parse.rs
- crates/objc2/src/macros/mod.rs
- crates/objc2/tests/use_macros.rs
- crates/test-ui/Cargo.toml
- crates/test-ui/src/main.rs
- crates/test-ui/ui/msg_send_missing_comma.rs
- crates/test-ui/ui/msg_send_missing_comma.stderr
This is done since the way the macro works currently is not actually valid [according to the reference](https://doc.rust-lang.org/reference/macros-by-example.html#follow-set-ambiguity-restrictions); in particular, an `expr` cannot come after an `ident`, see [this playground link for details](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4b46d5fea92dfe69fafc0a3f21fd4c31).
Also, the previous syntax wasn't even that consistent with Objective-C, we already had to put a comma after the receiver!
I may hold off on merging this until having attained wider adoption, since it is kinda unnecessary for users to deal with as the first thing when they upgrade...
> Deprecate using `msg_send!` without comma between arguments

- crates/icrate/tests/mutable_dictionary.rs
- crates/icrate/tests/mutable_set.rs
- crates/objc2/src/declare/mod.rs
- crates/objc2/src/exception.rs
- crates/objc2/src/runtime/nsobject.rs
While working on https://github.com/madsmtm/objc2/issues/306 and https://github.com/madsmtm/objc2/issues/337, I found the need to ensure that a few more properties of the runtime hold.
> Add more tests

- crates/header-translator/src/stmt.rs
- crates/icrate/CHANGELOG.md
- crates/icrate/examples/browser.rs
- crates/icrate/examples/delegate.rs
- crates/icrate/examples/metal.rs
- crates/icrate/src/fixes/Foundation/copying.rs
- crates/icrate/tests/renamed_protocols.rs
- crates/objc2/CHANGELOG.md
- crates/objc2/src/__macro_helpers/mod.rs
- crates/objc2/src/declare/mod.rs
- crates/objc2/src/macros/declare_class.rs
- crates/objc2/src/protocol_type.rs
- crates/objc2/src/runtime/nsobject.rs
- crates/objc2/src/runtime/nsproxy.rs
- crates/objc2/src/runtime/protocol_object.rs
- crates/tests/src/test_object.rs
Fix protocol names of renamed protocols `NSObjectProtocol`, `NSAccessibilityElementProtocol`, `NSTextAttachmentCellProtocol` and `NSFileProviderItemProtocol`.
This also fixes the issue with declaring conformance to the `NSObjectProtocol` in `declare_class!`, so that's really nice!
> Fix protocol names

- crates/header-translator/src/rust_type.rs
- crates/header-translator/src/stmt.rs
- crates/icrate/CHANGELOG.md
- crates/icrate/src/additions/Foundation/dictionary.rs
I think this has been possible since https://github.com/madsmtm/objc2/pull/419, I just forgot to remove these workarounds.
> Remove `NSCopying`/`NSMutableCopying` workarounds in header translator

- .github/workflows/ci.yml
- crates/header-translator/src/rust_type.rs
- crates/objc-sys/build.rs
- crates/objc-sys/src/lib.rs
- crates/objc-sys/src/various.rs
- crates/objc2/CHANGELOG.md
- crates/objc2/src/declare/mod.rs
- crates/objc2/src/macros/extern_class.rs
- crates/objc2/src/runtime/message_receiver.rs
- crates/objc2/src/runtime/mod.rs
- crates/objc2/src/runtime/nsobject.rs
- crates/objc2/src/runtime/nsproxy.rs
- crates/test-assembly/crates/test_declare_class/expected/apple-aarch64.s
- crates/test-assembly/crates/test_declare_class/expected/apple-armv7.s
- crates/test-assembly/crates/test_declare_class/expected/apple-armv7s.s
- crates/test-assembly/crates/test_declare_class/expected/apple-old-x86.s
- crates/test-assembly/crates/test_declare_class/expected/apple-x86.s
- crates/test-assembly/crates/test_declare_class/expected/apple-x86_64.s
- crates/test-ui/ui/declare_class_invalid_receiver.stderr
- crates/test-ui/ui/extern_class_root.stderr
- crates/test-ui/ui/implement_protocol_missing_super.stderr
- crates/test-ui/ui/msg_send_id_invalid_return.stderr
- crates/test-ui/ui/msg_send_invalid_error.stderr
- crates/test-ui/ui/msg_send_super_not_classtype.stderr
- crates/test-ui/ui/mutability_traits_unimplementable2.stderr
- crates/test-ui/ui/nsarray_bound_not_send_sync.stderr
- crates/test-ui/ui/nsarray_not_message.stderr
- crates/test-ui/ui/object_not_send_sync.stderr
A few smaller things I fixed while doing https://github.com/madsmtm/objc2/pull/521.
Split out to make reviewing easier.
> Prerequisites for redoing ivars

- crates/objc2-encode/CHANGELOG.md
- crates/objc2-encode/src/encoding.rs
- crates/objc2-encode/src/encoding_box.rs
- crates/objc2-encode/src/helper.rs
- crates/objc2-encode/src/parse.rs
- crates/objc2-encode/src/static_str.rs
- crates/objc2/src/runtime/method_encoding_iter.rs
- crates/test-fuzz/fuzz_targets/encoding_parse.rs
In https://github.com/rust-windowing/glutin/issues/1640 the encoding of the `CGLContextObj` object changed between versions of macOS. As such, this is something that we must be prepared to handle in our encoding comparison routines.
> Future-proof struct encodings

- crates/objc2-encode/CHANGELOG.md
- crates/objc2-encode/src/encoding.rs
- crates/objc2-encode/src/parse.rs
- crates/objc2/src/runtime/mod.rs
Instance variables include extended type information, we should find some way to represent this.
See: https://bou.io/ExtendedTypeInfoInObjC.html
> Fix instance variable object encoding

- crates/icrate/src/fixes/Foundation/copying.rs
- crates/objc2/CHANGELOG.md
- crates/objc2/src/macros/extern_protocol.rs
- crates/objc2/src/mutability.rs
- crates/objc2/src/runtime/nsobject.rs
- crates/objc2/src/runtime/protocol_object.rs
- crates/test-ui/ui/protocol_object_only_protocols.rs
- crates/test-ui/ui/protocol_object_only_protocols.stderr
Relax the `ProtocolType` requirement on `ProtocolObject`, which means we can now have protocol objects with auto traits, such as `ProtocolObject<dyn NSObjectProtocol + Send>`.
Protocols objects with multiple protocols are not yet possible.
Construction of these is still difficult, we'd have to somehow do `impl ImplementedBy<T: Any + Combination + Of + Traits> for dyn Any + Combination + Of + Traits`. But I suspect construction of these will be exceedingly rare anyhow, and at least it's better that you can _use_ them, if `icrate` constructs them for you.
TODO:
> Relax `ProtocolType` requirement on `ProtocolObject`

- .github/workflows/ci.yml
- crates/objc-sys/CHANGELOG.md
- crates/objc-sys/src/class.rs
- crates/objc-sys/src/lib.rs
- crates/objc-sys/src/libc.rs
- crates/objc-sys/src/method.rs
- crates/objc-sys/src/property.rs
- crates/objc-sys/src/protocol.rs
- crates/objc-sys/src/various.rs
- crates/objc2/CHANGELOG.md
- crates/objc2/Cargo.toml
- crates/objc2/examples/introspection.rs
- crates/objc2/src/__macro_helpers/declare_class.rs
- crates/objc2/src/lib.rs
- crates/objc2/src/macros/declare_class.rs
- crates/objc2/src/runtime/declare.rs
- crates/objc2/src/runtime/malloc.rs
- crates/objc2/src/runtime/mod.rs
- crates/test-ui/ui/msg_send_invalid_error.stderr
- crates/test-ui/ui/nsarray_not_message.stderr
- crates/tests/Cargo.toml
- crates/tests/src/test_declare_class_protocol.rs
- crates/tests/src/test_object.rs
- helper-scripts/test-local.sh
`malloc_buf` is [unmaintained and unsound](https://github.com/rustsec/advisory-db/issues/1635), and may be marked as such in the Rustsec Advisory Database in the future, which would be bad for our users; so we should really migrate to something else.
The alternatives [`mbox`](https://github.com/kennytm/mbox), [`malloced`](https://github.com/nvzqz/malloced) and [`malloc-array`](https://github.com/notflan/rs-malloc-array) are either also unsound (usually failing to handle `0`-length arrays properly), or not popular/maintained enough for me to be comfortable with them as a dependency.
So let's just roll our own implementation, it's not really _that_ complex anyhow (since we don't handle allocation, only deallocation), and we should be able to swap it out with `Box<_, MallocAllocator>` in the …
> Work towards removing `malloc_buf`

- Cargo.lock
- crates/block2/CHANGELOG.md
- crates/block2/src/abi.rs
- crates/block2/src/global.rs
- crates/block2/src/lib.rs
- crates/block2/src/rc_block.rs
- crates/block2/src/stack.rs
- crates/icrate/src/additions/Foundation/data.rs
- crates/test-assembly/crates/test_block/Cargo.toml
- crates/test-assembly/crates/test_block/expected/apple-aarch64.s
- crates/test-assembly/crates/test_block/expected/apple-armv7s.s
- crates/test-assembly/crates/test_block/expected/apple-x86.s
- crates/test-assembly/crates/test_block/expected/apple-x86_64.s
- crates/test-assembly/crates/test_block/expected/gnustep-x86.s
- crates/test-assembly/crates/test_block/expected/gnustep-x86_64.s
- crates/test-assembly/crates/test_block/lib.rs
- crates/tests/src/block.rs
- crates/tests/src/ffi.rs
- crates/tests/src/lib.rs
Part of https://github.com/madsmtm/objc2/issues/168. Fixes upstream https://github.com/SSheldon/rust-block/issues/9.
The way `block2` currently works is that you create the `StackBlock`, and then you must call `copy` to convert it to an `RcBlock`. This is very error-prone, especially since you can't ensure that Objective-C doesn't call `_Block_copy` when you pass your stack block to an external function, so forgetting to call `copy` usually ends up causing double-frees.
Instead, we should implement `StackBlock` to use `Clone` once `_Block_copy` is called, and for the cases where that's impossible, the user should construct the `RcBlock` directly.
> Fix block2 memory management

- crates/header-translator/src/availability.rs
- crates/header-translator/src/cache.rs
- crates/header-translator/src/method.rs
- crates/header-translator/src/stmt.rs
- crates/header-translator/translation-config.toml
- crates/icrate/CHANGELOG.md
- crates/icrate/src/common.rs
- crates/objc2/src/macros/extern_category.rs
- crates/objc2/src/macros/mod.rs
Categories are a way for Objective-C code to add extra methods to a class. There are basically two ways we could handle these in `header-translator`:
1. Emit `extern_methods!` directly on the class (done currently).
This breaks when the class is defined in a different library/framework than the category, because of Rust's coherence rules.
2. Create a trait, and implement that for the class (done in `uikit-sys`, and now by `extern_category!`).
One problem here is that the category name is not part of the API in Objective-C, so we actually have no stable name to refer to. Relatedly, it's annoying to have to import category traits with confusing names all the time.
Both approaches have issues, so I've tried to strike a nice balance; we now emit `extern_methods!` when the category is defined …
> Generate external categories

- crates/header-translator/src/cache.rs
- crates/header-translator/src/expr.rs
- crates/header-translator/src/rust_type.rs
- crates/header-translator/src/stmt.rs
- crates/header-translator/src/unexposed_attr.rs
- crates/icrate/CHANGELOG.md
- crates/icrate/src/additions/Foundation/mod.rs
- crates/icrate/src/additions/Foundation/not_found.rs
- crates/icrate/src/macros.rs
- crates/test-ui/ui/msg_send_invalid_error.stderr
- crates/test-ui/ui/nsarray_not_message.stderr
Part of https://github.com/madsmtm/objc2/issues/310, as we need to track more information to properly do that one.
> Refactor `Expr` handling in `header-translator`

- crates/header-translator/src/display_helper.rs
- crates/header-translator/src/lib.rs
- crates/header-translator/src/method.rs
- crates/header-translator/src/rust_type.rs
- crates/header-translator/src/stmt.rs
- crates/icrate/CHANGELOG.md
Basically had to rewrite the entire thing because I hadn't documented why the code was written like it was, which meant I couldn't remember. So this... Took a while, but I feel pretty confident it's at a better spot now.
> Refactor `rust_type.rs` so that typedefs carry their inner type

- crates/objc-sys/build.rs
- crates/objc-sys/src/class.rs
- crates/objc-sys/src/constants.rs
- crates/objc-sys/src/exception.rs
- crates/objc-sys/src/message.rs
- crates/objc-sys/src/method.rs
- crates/objc-sys/src/object.rs
- crates/objc-sys/src/property.rs
- crates/objc-sys/src/protocol.rs
- crates/objc-sys/src/rc.rs
- crates/objc-sys/src/selector.rs
- crates/objc-sys/src/types.rs
- crates/objc-sys/src/various.rs
Once https://github.com/rust-lang/rust/issues/80970 is in our MSRV, we should be able to completely remove the build script, so this is a step towards doing so.
> Reduce amount of custom cfgs in `objc-sys`

- crates/objc2/benches/autorelease.rs
- crates/objc2/src/rc/autorelease.rs
- crates/objc2/src/rc/id_forwarding_impls.rs
- crates/objc2/src/runtime/declare.rs
- crates/objc2/src/runtime/method_encoding_iter.rs
- crates/objc2/src/runtime/mod.rs
- framework-crates/objc2-foundation/src/array.rs
- framework-crates/objc2-foundation/src/data.rs
- framework-crates/objc2-foundation/src/number.rs
- framework-crates/objc2-foundation/src/set.rs
- framework-crates/objc2-foundation/src/string.rs
- framework-crates/objc2-foundation/src/tests/thread.rs
- framework-crates/objc2-foundation/src/value.rs
One part of this required a change other than semicolons to fix type inferencing in `crates/objc2/src/__macro_helpers/declared_ivars.rs`.
> clippy: Enable `semicolon_if_nothing_returned`

- crates/objc2-encode/src/encoding.rs
- crates/objc2-encode/src/encoding_box.rs
- crates/objc2-encode/src/helper.rs
- crates/objc2-encode/src/parse.rs
- crates/objc2-encode/src/static_str.rs
- crates/tests/build.rs
- crates/tests/extern/encode_utils.m
- crates/tests/extern/test_simd_return.m
- crates/tests/src/lib.rs
- crates/tests/src/test_encode_utils.rs
- crates/tests/src/test_simd_return.rs
Fixes https://github.com/madsmtm/objc2/issues/582 as far as we can right now, Rust/Clang/GCC still needs to figure out the ABI of these types when passing them across FFI.
Tested on the major architectures we support:
You can see a quick summary of the places that this currently doesn't work in the `test_simd_return.rs` test.
> Add SIMD support in encodings

- crates/objc2/CHANGELOG.md
- crates/objc2/Cargo.toml
- crates/objc2/src/runtime/declare.rs
- crates/objc2/src/test_utils.rs
- crates/objc2/src/verify.rs
Fixes https://github.com/madsmtm/objc2/issues/566.
Unsure if this is the correct path forwards.
Do signed-ness ever matter ABI-wise? The Rust docs [says](https://doc.rust-lang.org/nightly/std/primitive.fn.html) on ABI of `i32` vs `u32`:
> on some targets, the calling conventions for these types differ in terms of what they guarantee for the remaining bits in the register that are not used by the value.
But is that relevant for any platforms we target? And does it matter for types like `usize`/`isize`, which won't _have_ remaining bits left in any registers?
> Ignore signed-ness in encoding

- framework-crates/objc2-foundation/src/thread.rs
Previous, the "is_main_thread" function would always make a call to the
"NSThread::isMainThread_class" function to determine if the current thread is
the main thread. This requires an objc dispatch call every time it is called. As
this function or MainThreadMarker is used frequently throughout the objc2
ecosystem it takes a lot of time.
Crucially, the main-threadedness of a thread will never change. So we can avoid
making this objc call every time if we cache this state in a thread-local
variable. This commit does that for is_main_thread, and also makes it so
MainThreadMarker::new() uses the is_main_thread function.
Inspired by the code in async-task here:
https://github.com/smol-rs/async-task/blob/3065c372e1ef1611230195ad7f3aae80ffde8261/src/runnable.rs#L421-L428
> Optimize is_main_thread by using a libc call

- crates/objc2/src/exception.rs
- crates/objc2/src/runtime/__nsstring.rs
- crates/objc2/src/runtime/protocol_object.rs
- framework-crates/objc2-foundation/examples/basic_usage.rs
- framework-crates/objc2-foundation/src/string.rs
- framework-crates/objc2-foundation/src/tests/dictionary.rs
- framework-crates/objc2-foundation/src/tests/mutable_array.rs
- framework-crates/objc2-foundation/src/tests/mutable_string.rs
- framework-crates/objc2-foundation/src/tests/set.rs
- framework-crates/objc2-foundation/src/tests/string.rs
`-[NSString UTF8String]` (or the equivalent `NSString::as_str`) is used several times in our implementation, but when transitioning to https://github.com/madsmtm/objc2/issues/563, we must ensure that this usage is still sound even if the string is interior mutable.
Luckily, Foundation already ensures this for us by checking if the string is mutable in the implementation of `UTF8String` (and does so since macOS 10.6, I checked by downloading and disassembling the old binaries), so we needn't worry here.
> Improve documentation and usage of `-[NSString UTF8String]`

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- crates/block2/src/global.rs
- crates/header-translator/src/main.rs
- crates/test-assembly/crates/test_declare_class/expected/apple-aarch64.s
- crates/test-assembly/crates/test_declare_class/expected/apple-x86_64.s
- crates/test-assembly/crates/test_fast_enumeration/expected/apple-aarch64.s
- crates/test-assembly/crates/test_fast_enumeration/expected/apple-armv7s.s
- crates/test-assembly/crates/test_fast_enumeration/expected/apple-x86.s
- crates/test-assembly/crates/test_fast_enumeration/expected/apple-x86_64.s
- crates/test-assembly/crates/test_fast_enumeration/expected/gnustep-x86.s
- crates/test-assembly/crates/test_fast_enumeration/expected/gnustep-x86_64.s
- crates/test-ui/src/main.rs
- crates/test-ui/ui/declare_class_invalid_type.stderr
- crates/test-ui/ui/extern_class_feature_flag.rs
- crates/test-ui/ui/extern_methods_feature_flag.rs
- crates/test-ui/ui/extern_methods_variadic.stderr
- crates/test-ui/ui/msg_send_not_allowed_mutable.stderr
- crates/test-ui/ui/mutability_traits_unimplementable2.stderr
- crates/test-ui/ui/ns_string_output_not_const.stderr
- crates/tests/src/test_encode_utils.rs
- framework-crates/objc2-foundation/src/tests/value.rs
- framework-crates/objc2-input-method-kit/src/lib.rs
- framework-crates/objc2-metal/src/device.rs
- framework-crates/objc2-metal/src/private.rs
- rust-toolchain.toml
Assembly test changes are:
- The ability to eliminate an empty `Drop` call in `declare_class!` test.
- Code reordering in fast enumeration for unclear reasons?
Clippy lints are positive.
UI test changes are the usual reordering because of current nondeterminism, possibly fixed by https://github.com/rust-lang/rust/pull/120812, and a few cleanups. Note that I had to set `RUSTFLAGS` to something while running `trybuild`, since otherwise it outputs the full list of suggested traits, see https://github.com/dtolnay/trybuild/blob/b1b7064b7ad11e0ab563e9eb843651d86e4545b7/src/cargo.rs#L44.
> Update to nightly 2024-06-13

- Cargo.lock
- crates/block2/CHANGELOG.md
- crates/block2/Cargo.toml
- crates/block2/src/abi.rs
- crates/block2/src/debug.rs
- crates/block2/src/encoding.rs
- crates/block2/src/global.rs
- crates/block2/src/lib.rs
- crates/block2/src/rc_block.rs
- crates/block2/src/stack.rs
- crates/block2/src/traits.rs
- crates/objc2-encode/CHANGELOG.md
- crates/objc2-encode/src/encoding.rs
- crates/objc2-encode/src/helper.rs
- crates/test-ui/ui/block_lifetimes_independent.rs
- crates/test-ui/ui/block_lifetimes_independent.stderr
- crates/test-ui/ui/lifetime_of_closure_tied_to_block.rs
- crates/test-ui/ui/lifetime_of_closure_tied_to_block.stderr
- crates/test-ui/ui/stack_block_requires_clone.stderr
- crates/test-ui/ui/stack_block_with_encoding_requires_clone.rs
- crates/test-ui/ui/stack_block_with_encoding_requires_clone.stderr
- crates/tests/src/block.rs
Hey @madsmtm!
This is an attempt to contribute to #442, by adding the ability to manually provide a block encoding to its constructor so that it sets `BLOCK_HAS_SIGNATURE` and saves the string properly.
Included:
* New `StackBlock::with_encoding`.
* New `RcBlock::with_encoding`.
* `block2::traits::ManualBlockEncoding` is the smuggling trait.
* String check on `cfg(debug_assertions)`: a bit too strict for now, but can be relaxed later on by implementing a dedicated parser and equivalence checking.
* Updated and new tests.
Cheers,
Paul.
> Manual block encodings

- crates/objc2/CHANGELOG.md
- crates/objc2/Cargo.toml
- crates/objc2/src/downcast.rs
- crates/objc2/src/exception.rs
- crates/objc2/src/lib.rs
- crates/objc2/src/macros/declare_class.rs
- crates/objc2/src/macros/extern_class.rs
- crates/objc2/src/rc/retained.rs
- crates/objc2/src/runtime/declare.rs
- crates/objc2/src/runtime/mod.rs
- crates/objc2/src/runtime/nsobject.rs
- crates/objc2/src/runtime/nsproxy.rs
- crates/objc2/src/runtime/protocol_object.rs
- crates/test-fuzz/fuzz_targets/mut_while_iter.rs
- crates/test-ui/ui/downcast_generic.rs
- crates/test-ui/ui/downcast_generic.stderr
- crates/tests/src/test_object.rs
- framework-crates/objc2-app-kit/examples/nspasteboard.rs
- framework-crates/objc2-foundation/src/bundle.rs
- framework-crates/objc2-foundation/src/exception.rs
- framework-crates/objc2-foundation/src/iter.rs
- framework-crates/objc2-foundation/src/tests/attributed_string.rs
- framework-crates/objc2-foundation/src/tests/mutable_string.rs
- framework-crates/objc2-foundation/src/tests/string.rs
Add downcasting capability based on `isKindOfClass:`.
> Add downcasting capability based on `isKindOfClass:`

- Cargo.lock
- crates/objc2/CHANGELOG.md
- crates/objc2/src/__macro_helpers/mod.rs
- crates/objc2/src/__macro_helpers/os_version.rs
- crates/objc2/src/__macro_helpers/os_version/apple.rs
- crates/objc2/src/ffi/mod.rs
- crates/objc2/src/lib.rs
- crates/objc2/src/macros/available.rs
- crates/objc2/src/macros/mod.rs
- crates/objc2/src/runtime/nsobject.rs
- crates/test-assembly/crates/test_available/Cargo.toml
- crates/test-assembly/crates/test_available/expected/apple-aarch64.s
- crates/test-assembly/crates/test_available/expected/apple-armv7s.s
- crates/test-assembly/crates/test_available/expected/apple-old-x86.s
- crates/test-assembly/crates/test_available/expected/apple-x86.s
- crates/test-assembly/crates/test_available/expected/apple-x86_64.s
- crates/test-assembly/crates/test_available/expected/gnustep-x86.s
- crates/test-assembly/crates/test_available/expected/gnustep-x86_64.s
- crates/test-assembly/crates/test_available/lib.rs
- crates/test-ui/ui/available_invalid.rs
- crates/test-ui/ui/available_invalid.stderr
- crates/test-ui/ui/available_same_os.rs
- crates/test-ui/ui/available_same_os.stderr
- crates/test-ui/ui/available_unknown_os.rs
- crates/test-ui/ui/available_unknown_os.stderr
Add macro for runtime availability checking, with static assertions against the deployment target that allows eliding the runtime checks when unnecessary.
Part of https://github.com/madsmtm/objc2/issues/266.
Usage:
```rust
if available!(macos = 15.0, ios = 18.0, tvos = 18.0, watchos = 11.0, visonos = 2.0) {
// Use API added in Xcode 16.0
}
// Or
#[cfg(target_os = "macos")]
if available!(macos = 15.0) {
// Use API that's only relevant on macOS
}
// Or
if available!(macos = 10.7, ..) { // Note the `..`
// Use API introduced in macOS 10.7, and take this branch on all other platforms too
}
```
Runtime lookup implementation tested on:
- macOS 14.7, M1 Macbook
- `aarch64-apple-darwin`
- `aarch64-apple-ios-macabi`
- `x86_64-apple-ios-macabi`
- `aarch64-apple-ios-sim`
- macOS 10.14.6, Intel …
> Implement runtime availability checking

- crates/objc2/src/macros/mod.rs
- crates/test-assembly/crates/test_declare_class/expected/apple-aarch64.s
- crates/test-assembly/crates/test_declare_class/expected/apple-x86_64.s
- crates/test-assembly/crates/test_extern_protocol/expected/apple-aarch64.s
- crates/test-assembly/crates/test_extern_protocol/expected/apple-armv7s.s
- crates/test-assembly/crates/test_extern_protocol/expected/apple-old-x86.s
- crates/test-assembly/crates/test_extern_protocol/expected/apple-x86.s
- crates/test-assembly/crates/test_extern_protocol/expected/apple-x86_64.s
- crates/test-assembly/crates/test_msg_send_static_sel/expected/apple-aarch64.s
- crates/test-assembly/crates/test_msg_send_static_sel/expected/apple-armv7s.s
- crates/test-assembly/crates/test_msg_send_static_sel/expected/apple-old-x86.s
- crates/test-assembly/crates/test_msg_send_static_sel/expected/apple-x86.s
- crates/test-assembly/crates/test_msg_send_static_sel/expected/apple-x86_64.s
- crates/test-assembly/crates/test_static_class/expected/apple-aarch64.s
- crates/test-assembly/crates/test_static_class/expected/apple-armv7s.s
- crates/test-assembly/crates/test_static_class/expected/apple-old-x86.s
- crates/test-assembly/crates/test_static_class/expected/apple-x86.s
- crates/test-assembly/crates/test_static_class/expected/apple-x86_64.s
- crates/test-assembly/crates/test_static_sel/expected/apple-aarch64.s
- crates/test-assembly/crates/test_static_sel/expected/apple-armv7s.s
- crates/test-assembly/crates/test_static_sel/expected/apple-old-x86.s
- crates/test-assembly/crates/test_static_sel/expected/apple-x86.s
- crates/test-assembly/crates/test_static_sel/expected/apple-x86_64.s
Closes #667 
I think there won't be a person to explain why objc ABI 2 uses `no_dead_strip` in a short time. Maybe it is better to remove it first. If there were more problems, we would know why it is necessary:)
> Remove `no_dead_strip` marks

- framework-crates/objc2-vision/translation-config.toml
This is far from comprehensive but is all of the functions that I am currently using from vision framework.
I tried following the guide in [the README](https://github.com/madsmtm/objc2/blob/master/crates/header-translator/README.md#adding-a-new-framework-crate) - none of these functions have any meaningful limitations on their parameters.
The only point that I am unsure of is the last one:
```
If the method can throw an exception if provided with invalid inputs, it is not safe. Consider declaring a helper method that checks the preconditions first!
```
I would really like to add the function `VNImageRequestHandler::performRequests_error` as a safe function as well. It can throw an exception if it gets invalid parameters, but the rust function returns a `Result<(), Retained<NSError>>` so …
> Remove unsafe from some vision framework functions

- crates/objc2/src/rc/mod.rs
- crates/objc2/src/rc/retained.rs
- crates/objc2/src/rc/weak.rs
As part of #617.
With this, 0.6 should be in a good position to be delivered, or are there still a lot of things to do? What I see in https://github.com/madsmtm/objc2/milestone/6 seems that it could be optional while the important changes that are already completed would be nice if published and back-porting things I would need in a fork would be cumbersome.
> Chore: Fully deprecate `objc2::rc::Id`

- crates/dispatch2/CHANGELOG.md
- crates/dispatch2/src/group.rs
- crates/dispatch2/src/queue.rs
> fix(dispatch2): Add `'static` bound to `exec_async`

- crates/dispatch2/CHANGELOG.md
- crates/dispatch2/src/group.rs
- crates/dispatch2/src/lib.rs
- crates/dispatch2/src/macros.rs
- crates/dispatch2/src/main_thread_bound.rs
- crates/dispatch2/src/object.rs
- crates/dispatch2/src/once.rs
- crates/dispatch2/src/queue.rs
- crates/dispatch2/src/retained.rs
- crates/dispatch2/src/retained/forwarding_impls.rs
- crates/dispatch2/src/semaphore.rs
- crates/dispatch2/src/workloop.rs
- crates/objc2/src/rc/retained_forwarding_impls.rs
Refactor `dispatch2` to use the `DispatchRetained<T>` pattern instead of types owning the retain count internally. This should allow us to use Dispatch types in the auto-generated headers. See https://github.com/madsmtm/objc2/pull/681#issuecomment-2559982918 for why we don't use a more general approach to these `*Retained` types.
I've also decided to prefix types with "Dispatch", to better match Swift, and to allow easily glob-importing from `dispatch2` without fear that the symbols will clash with something else. This isn't that "rusty", but it plays much nicer with the rest of the `objc2` ecosystem, and matches what Swift does.
It's also clearer at the usage-site. Compare:
```rust
// Hmm, what queue are we referring to?
Queue::main().exec_sync(|| ...);
// Ah, it's a Dispatch queue. …
```
> Refactor `dispatch2`

- crates/header-translator/src/config.rs
- crates/header-translator/src/method.rs
- framework-crates/objc2-io-usb-host/translation-config.toml
This PR partially resolves https://github.com/madsmtm/objc2/issues/753#issuecomment-2871949083 by adding options in translation-config.toml to override the nullability of method argument and return types (including properties)
> config option to override method argument and return type nullability

- framework-crates/objc2-io-kit/Cargo.toml
- framework-crates/objc2-io-kit/src/lib.rs
- framework-crates/objc2-io-kit/src/macros.rs
- framework-crates/objc2-io-kit/translation-config.toml
This PR adds power management for IOKit.
1. Verified that `iokit_family_err!` macro works with objc:
```objc
int value = kIOPSFamilyCodeFirewire;
NSLog(@"Value: %d", value);
```
and Rust test:
```rs
#[test]
fn test() {
let value = crate::kIOPSFamilyCodeFirewire;
std::println!("kIOPSFamilyCodeFirewire = {}", value);
}
```
Both emit `-536838144`.
1. Some of the constants from `IOPM.h` use `iokit_family_msg` macro which for some reason is not being picked up so I simply decided to skip those defines for now
1. `iokit_family_msg` and `iokit_family_err` are used in different contexts. The latter is often used in enums which default to C `int`. But `iokit_family_msg` seems to be used in contexts where it's expected to be cast to `UInt32`. Go figure..
_Generated with XCode 16.2, sorry I can't …
> iokit: enable power management mod
