madsmtm/objc2

.github/workflows/gnustep.yml, block2/README.md, block2/src/lib.rs, objc-sys/CHANGELOG.md, objc-sys/README.md, objc-sys/build.rs, objc-sys/src/class.rs, objc2-encode/src/encoding.rs, objc2-foundation/src/array.rs, objc2-foundation/src/enumerator.rs, objc2-foundation/src/string.rs, objc2/src/declare.rs, objc2/src/message/gnustep.rs, objc2/src/message/mod.rs, objc2/src/rc/id.rs, objc2/src/runtime.rs, objc2/src/test_utils.rs, tests/src/ffi.rs, tests/src/lib.rs
Things that have been accumulating in my local git stashes, but didn't really warrant a PR on their own.
The biggest is probably:
> Fix sending nil messages to super on GNUStep, and clean up documentation
=> Various small fixes

block-sys/Cargo.toml, block2/Cargo.toml, objc-sys/Cargo.toml, objc-sys/build.rs, objc2-encode/Cargo.toml, objc2-foundation/Cargo.toml, objc2/Cargo.toml, objc2/build.rs
Part of https://github.com/madsmtm/objc2/issues/32. Not quite sure whether adding all ish-supported targets in `package.metadata.docs.rs.targets` is appropriate, but I've done it for the most important crates for now at least.
=> Fix docs.rs setup

objc2-encode/CHANGELOG.md, objc2-encode/README.md, objc2-encode/examples/ns_uinteger.rs, objc2-encode/examples/opaque_type.rs, objc2-encode/src/encoding.rs, objc2-encode/src/parse.rs, objc2-foundation/src/value.rs, objc2/examples/introspection.rs, objc2/src/message/verify.rs, objc2/src/runtime.rs
Part of https://github.com/madsmtm/objc2/issues/68 (see https://github.com/madsmtm/objc2/issues/68#issuecomment-959430359)
=> `Encoding` comparison fixes

objc2/CHANGELOG.md, objc2/src/message/mod.rs
=> Implement `MessageReceiver` and `Message` for `ManuallyDrop`

Cargo.toml, block-sys/CHANGELOG.md, block-sys/Cargo.toml, block-sys/src/lib.rs, block2/CHANGELOG.md, block2/Cargo.toml, block2/src/lib.rs, objc-sys/CHANGELOG.md, objc-sys/Cargo.toml, objc-sys/src/lib.rs, objc2-encode/CHANGELOG.md, objc2-encode/Cargo.toml, objc2-encode/src/lib.rs, objc2-foundation/CHANGELOG.md, objc2-foundation/Cargo.toml, objc2-foundation/src/lib.rs, objc2/CHANGELOG.md, objc2/Cargo.toml, objc2/src/lib.rs
Bump all crates. Will release on the merge commit.
=> New versions

Cargo.toml, block-sys/Cargo.toml, block2/Cargo.toml, objc-sys/Cargo.toml, objc-sys/README.md, objc2-encode/Cargo.toml, objc2-foundation/Cargo.toml, objc2/Cargo.toml, objc2/examples/talk_to_me.rs, objc2/src/declare.rs, objc2/src/message/apple/arm.rs, objc2/src/message/apple/mod.rs, objc2/src/message/apple/x86_64.rs, objc2/src/message/mod.rs, objc2/src/rc/id.rs, objc2/src/rc/weak_id.rs, objc2/src/runtime.rs, tests/Cargo.toml, tests/assembly/test_msg_send_zero_cost/Cargo.toml, tests/assembly/test_retain_autoreleased/Cargo.toml
Various smaller things that didn't really warrant a PR on their own.
=> Various improvements

tests/Cargo.toml, tests/build.rs, tests/extern/test_object.m, tests/src/lib.rs, tests/src/test_object.rs
In particular I wanted to make sure that instance variables actually work as they should. But this can also be a starting point for testing more complex interactions (for example synthetized properties and their atomic-ness).
=> Test runtime introspection with a class created by Objective-C

objc2/CHANGELOG.md, objc2/src/declare.rs, objc2/src/message/mod.rs, objc2/src/test_utils.rs
Builds upon #158.
Allows us to more easily change implementation details in the future.
=> Future proof a few more traits

objc2-encode/CHANGELOG.md, objc2-encode/src/encoding.rs, objc2-foundation/src/enumerator.rs, objc2-foundation/src/thread.rs, objc2/src/declare.rs, tests/src/test_encode_utils.rs
Rename `Encoding::C_U_LONG` -> `Encoding::C_ULONG` and add a few `ClassBuilder` tests.
=> Small fixes

README.md, objc2-foundation/examples/nspasteboard.rs, objc2-foundation/examples/nsspeechsynthesizer.rs, objc2/examples/talk_to_me.rs
Improve main README.
Add `NSPasteboard` and `NSSpeechSynthesizer` examples.
=> Various documentation improvements

block2/CHANGELOG.md, block2/src/debug.rs, block2/src/global.rs, block2/src/lib.rs, tests/build.rs, tests/extern/block_utils.c, tests/src/ffi.rs
Improves debugging experience when dealing with blocks
=> Implement `Debug` for all block structures

.github/workflows/ci.yml, tests/ui/msg_send_id_invalid_method.stderr
Also allow warnings in UI tests
=> Fix `nightly` UI tests

.github/workflows/ci.yml, objc2-foundation/CHANGELOG.md, objc2-foundation/Cargo.toml, objc2-foundation/src/array.rs, objc2-foundation/src/attributed_string.rs, objc2-foundation/src/data.rs, objc2-foundation/src/dictionary.rs, objc2-foundation/src/exception.rs, objc2-foundation/src/lib.rs, objc2-foundation/src/mutable_array.rs, objc2-foundation/src/mutable_attributed_string.rs, objc2-foundation/src/mutable_data.rs, objc2-foundation/src/mutable_string.rs, objc2-foundation/src/object.rs, objc2-foundation/src/process_info.rs, objc2-foundation/src/string.rs, objc2-foundation/src/thread.rs, objc2-foundation/src/uuid.rs, objc2-foundation/src/value.rs, objc2-foundation/src/zone.rs, objc2/src/rc/id_forwarding_impls.rs
See changelog and commit history for details.
=> Improve `objc2-foundation`

objc2-foundation/src/declare_macro.rs, objc2-foundation/src/macros.rs
Also improves the documentation of the macro.
=> Allow specifying fields in `extern_class!`

test-ui/Cargo.toml, test-ui/ui/autoreleasepool_not_send_sync.stderr, test-ui/ui/fn_ptr_reference_encode.stderr, test-ui/ui/fn_ptr_reference_method.stderr, test-ui/ui/fn_ptr_reference_method2.stderr, test-ui/ui/global_block_not_encode.stderr, test-ui/ui/invalid_msg_send.stderr, test-ui/ui/invalid_msg_send_super.stderr, test-ui/ui/invalid_sel.stderr, test-ui/ui/mainthreadmarker_not_send_sync.stderr, test-ui/ui/msg_send_id_invalid_method.stderr, test-ui/ui/msg_send_id_invalid_receiver.stderr, test-ui/ui/msg_send_id_invalid_return.stderr, test-ui/ui/msg_send_id_underspecified.stderr, test-ui/ui/msg_send_mutable.stderr, test-ui/ui/msg_send_no_return_type.stderr, test-ui/ui/msg_send_not_encode.stderr, test-ui/ui/msg_send_only_message.stderr, test-ui/ui/nsarray_bound_not_send_sync.stderr, test-ui/ui/nsstring_as_str_use_after_release.stderr, test-ui/ui/nsstring_as_str_use_outside_pool.stderr, test-ui/ui/nsvalue_f32_not_eq.stderr, test-ui/ui/object_not_send_sync.stderr
A recent version of `trybuild` changed line number handling to allow this
=> Remove line numbers from UI tests

.github/workflows/ci.yml, objc2/src/declare.rs
Also got my test setup to work on a real iOS device again, yay!
=> Update `cargo-dinghy` to v0.6.0

objc2/src/macros/declare_class.rs, objc2/src/macros/extern_class.rs
Introduced in https://github.com/madsmtm/objc2/pull/237
=> Fix inheritance in `declare_class!` and `extern_class!` macros

test-ui/ui/add_method_no_bool.stderr, test-ui/ui/autoreleasepool_not_send_sync.stderr, test-ui/ui/extern_class_not_zst.stderr, test-ui/ui/extern_methods_wrong_arguments.stderr, test-ui/ui/fn_ptr_reference_encode.stderr, test-ui/ui/fn_ptr_reference_method.stderr, test-ui/ui/fn_ptr_reference_method2.stderr, test-ui/ui/invalid_msg_send.stderr, test-ui/ui/invalid_msg_send_super.stderr, test-ui/ui/invalid_ns_string_input.stderr, test-ui/ui/msg_send_id_alloc_init_different.stderr, test-ui/ui/msg_send_id_invalid_method.stderr, test-ui/ui/msg_send_id_invalid_receiver.stderr, test-ui/ui/msg_send_id_invalid_return.stderr, test-ui/ui/msg_send_mutable.stderr, test-ui/ui/msg_send_not_encode.stderr, test-ui/ui/msg_send_super_not_classtype.stderr, test-ui/ui/ns_string_not_const.stderr, test-ui/ui/nsarray_bound_not_send_sync.stderr, test-ui/ui/nsstring_as_str_use_after_release.stderr, test-ui/ui/object_not_send_sync.stderr
Using the new `trybuild v1.0.66`, see https://github.com/dtolnay/trybuild/pull/194.
=> Update indentation in UI tests

.github/workflows/ci.yml, crates/objc2-encode/src/encode.rs, crates/test-ui/ui/invalid_msg_send.stderr, crates/test-ui/ui/invalid_ns_string_input.stderr, crates/test-ui/ui/invalid_sel.stderr, crates/test-ui/ui/ns_string_not_const.stderr
The latest `nightly` doesn't work on macOS Mojave, see https://github.com/rust-lang/rust/issues/104570, so I had to manually update the UI tests
=> Fix various CI issues

crates/block2/CHANGELOG.md, crates/block2/src/concrete_block.rs, crates/objc-sys/CHANGELOG.md, crates/objc-sys/README.md, crates/objc-sys/build.rs, crates/objc2-encode/CHANGELOG.md, crates/objc2-encode/src/encode.rs, crates/objc2/CHANGELOG.md, crates/objc2/CHANGELOG_FOUNDATION.md, crates/objc2/Cargo.toml, crates/objc2/examples/delegate.rs, crates/objc2/examples/nspasteboard.rs, crates/objc2/examples/speech_synthesis.rs, crates/objc2/src/foundation/copying.rs, crates/objc2/src/foundation/zone.rs, crates/objc2/src/macros.rs, crates/objc2/src/message/mod.rs, crates/objc2/tests/no_prelude.rs, crates/objc2/tests/use_macros.rs, crates/test-assembly/Cargo.toml, crates/test-assembly/crates/test_ns_string/Cargo.toml, crates/test-assembly/crates/test_ns_string/lib.rs, crates/test-ui/Cargo.toml, crates/test-ui/src/main.rs, crates/test-ui/ui/msg_send_id_invalid_method.rs, crates/test-ui/ui/msg_send_id_invalid_method.stderr, helper-scripts/test-local.fish
A collection of smaller improvements and fixes I had over time stashed away
=> Various fixes

crates/icrate/src/common.rs, crates/icrate/src/lib.rs, crates/objc2-encode/CHANGELOG.md, crates/objc2-encode/src/encode.rs, crates/objc2-encode/src/lib.rs, crates/objc2/CHANGELOG.md, crates/objc2/src/runtime.rs, crates/test-ui/ui/invalid_option_encode_impl.rs, crates/test-ui/ui/invalid_option_encode_impl.stderr
=> Add `OptionEncode` and `impl Encode for Option<Sel>`

.github/workflows/ci.yml, crates/test-ui/ui/extern_methods_invalid_type.stderr, crates/test-ui/ui/msg_send_id_alloc_init_different.stderr, crates/test-ui/ui/msg_send_id_invalid_receiver.stderr, crates/test-ui/ui/msg_send_id_invalid_return.stderr, crates/test-ui/ui/msg_send_id_no_return_type.stderr, crates/test-ui/ui/msg_send_id_underspecified.stderr, crates/test-ui/ui/msg_send_id_unwrap.stderr, crates/test-ui/ui/msg_send_invalid_error.stderr, crates/test-ui/ui/msg_send_no_return_type.stderr, crates/test-ui/ui/msg_send_not_encode.stderr, crates/test-ui/ui/msg_send_super_not_classtype.stderr, crates/test-ui/ui/msg_send_underspecified_error.stderr
The UI tests are strictly improvements, so nothing to report upstream there
=> Fix CI and update UI tests

crates/objc2/CHANGELOG.md, crates/objc2/src/declare.rs, crates/objc2/src/declare/declare_class_tests.rs, crates/objc2/src/macros.rs, crates/objc2/src/macros/declare_class.rs, crates/objc2/src/macros/extern_methods.rs, crates/objc2/src/rc/test_object.rs, crates/objc2/tests/no_prelude.rs, crates/objc2/tests/use_macros.rs, crates/test-ui/ui/declare_class_classtype_imported.rs, crates/test-ui/ui/invalid_msg_send.stderr, crates/test-ui/ui/nsarray_bound_not_send_sync.stderr, crates/test-ui/ui/object_not_send_sync.stderr, crates/test-ui/ui/wrong_optional.rs, crates/test-ui/ui/wrong_optional.stderr
Reported in https://github.com/madsmtm/objc2/issues/317#issue-1514849992
=> Allow empty structs in `declare_class!`

crates/header-translator/src/rust_type.rs, crates/test-ui/ui/msg_send_id_alloc_init_different.stderr, crates/test-ui/ui/msg_send_id_invalid_return.stderr
=> Update nightly UI tests and nightly clippy

Cargo.lock, crates/header-translator/Cargo.toml, crates/header-translator/src/lib.rs, crates/header-translator/src/method.rs, crates/header-translator/src/stmt.rs
Update of https://github.com/madsmtm/objc2/pull/335 pending changes from #342.
=> Snake case arguments

crates/header-translator/src/library.rs
I noticed this caused problems when trying to translate some frameworks.
=> Handle file names with "+" (translate to "_")

crates/header-translator/translation-config.toml, crates/icrate/src/WebKit/fixes.rs, crates/icrate/src/WebKit/mod.rs
Just a small fix for the WebKit bindings which I noticed while working on the browser example.
=> Add fix for WKNavigationAction::sourceFrame

.github/workflows/ci.yml, crates/objc2/Cargo.toml, crates/test-ui/ui/declare_class_invalid_type2.stderr, crates/test-ui/ui/extern_methods_invalid_type.stderr, crates/test-ui/ui/msg_send_id_alloc_init_different.stderr, crates/test-ui/ui/msg_send_id_invalid_receiver.stderr, crates/test-ui/ui/msg_send_id_invalid_return.stderr, crates/test-ui/ui/msg_send_invalid_error.stderr
The compiler UI is only improvements IMO
=> Update nightly Rust version and fix `objc2` docs.rs build

.github/workflows/ci.yml, Cargo.lock, crates/header-translator/src/data/macros.rs, crates/objc2/src/macros/mod.rs, crates/test-ui/ui/add_method_no_bool.stderr, crates/test-ui/ui/autoreleasepool_not_send_sync.stderr, crates/test-ui/ui/declare_add_bad_method.stderr, crates/test-ui/ui/declare_class_invalid_receiver.stderr, crates/test-ui/ui/declare_class_mut_self_not_mutable.stderr, crates/test-ui/ui/extern_class_wrong_mutability.stderr, crates/test-ui/ui/extern_methods_invalid_type.stderr, crates/test-ui/ui/fn_ptr_reference_method.stderr, crates/test-ui/ui/invalid_msg_send.stderr, crates/test-ui/ui/main_thread_only_not_allocable.stderr, crates/test-ui/ui/mainthreadmarker_not_send_sync.stderr, crates/test-ui/ui/msg_send_invalid_error.stderr, crates/test-ui/ui/msg_send_not_encode.stderr, crates/test-ui/ui/msg_send_super_not_classtype.stderr, crates/test-ui/ui/msg_send_underspecified_error.stderr, crates/test-ui/ui/mutable_id_not_clone_not_retain.stderr, crates/test-ui/ui/not_writeback.stderr, crates/test-ui/ui/nsarray_bound_not_send_sync.stderr, crates/test-ui/ui/nsobject_not_mutable.stderr, crates/test-ui/ui/nsstring_as_str_use_after_release.stderr, crates/test-ui/ui/object_not_send_sync.stderr, fuzz/Cargo.lock, helper-scripts/run-assembly-tests.sh
The UI tests are mostly an improvement, so that's nice!
=> Update nightly Rust and update dependencies

.github/workflows/ci.yml
=> Use install-action to install cargo-dinghy

crates/objc2/CHANGELOG.md, crates/objc2/src/__macro_helpers/mod.rs, crates/objc2/src/declare/mod.rs, crates/objc2/src/message/mod.rs, crates/objc2/src/runtime/mod.rs
Improve the documentation, add `Display` and `Debug` impls, and add a bit of `unsafe` functionality.
=> Improve `objc2::runtime`

crates/icrate/Cargo.toml, crates/icrate/examples/browser.rs, crates/icrate/examples/metal.rs
This is just some small fixes for the `metal` example and then a rewrite of the `browser` example to use deferred initialization via `RefCell` like with the `metal` example.
=> More refactoring for examples

crates/header-translator/src/data/AppKit.rs, crates/header-translator/src/data/Foundation.rs, crates/header-translator/src/data/macros.rs, crates/header-translator/src/method.rs, crates/header-translator/translation-config.toml, crates/icrate/CHANGELOG.md, crates/icrate/examples/browser.rs, crates/icrate/examples/delegate.rs, crates/icrate/examples/metal.rs, crates/icrate/src/additions/AppKit/mod.rs
Make various things that is used used by `winit` safe.
=> Add data from `winit`

.github/workflows/ci.yml, crates/dispatch2/translation-config.toml, crates/objc2/src/topics/about_generated/CHANGELOG.md, crates/objc2/src/topics/about_generated/README.md, framework-crates/objc2-accessibility/Cargo.toml, framework-crates/objc2-accessibility/translation-config.toml, framework-crates/objc2-app-kit/Cargo.toml, framework-crates/objc2-core-graphics/Cargo.toml, framework-crates/objc2-screen-capture-kit/Cargo.toml, framework-crates/objc2-sensitive-content-analysis/Cargo.toml, framework-crates/objc2-ui-kit/Cargo.toml, framework-crates/objc2-ui-kit/translation-config.toml, framework-crates/objc2-web-kit/Cargo.toml
Needs GitHub actions to update to Xcode 16.2 too. They currently only have the release candidate merged: https://github.com/actions/runner-images/pull/11134.
EDIT: Xcode 16.2 in GH actions PR is up: https://github.com/actions/runner-images/pull/11179
=> Update to Xcode 16.2

framework-crates/objc2-io-kit/Cargo.toml, framework-crates/objc2-io-kit/translation-config.toml
~~This is a draft PR. It should be REBASED after the generated pr got merged: https://github.com/madsmtm/objc2-generated/pull/12.~~
This is a PR for enabling PowerState in IOKit.
I manually tested those on https://github.com/gety-ai/powerstate/blob/main/src/os_impl/macos.rs, which works as expected
=> feat(io-kit): generate power state
